
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 278
#define YY_END_OF_BUFFER 279
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[697] =
    {   0,
        0,    0,  279,  277,  276,  275,  185,  277,  274,  185,
      186,  189,  190,    3,    1,  272,    2,    4,  199,  187,
      273,   26,   20,   27,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  197,   73,  198,  200,
      271,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  191,   19,  192,   15,  193,  194,
       25,    0,  188,    0,    0,    0,    0,    0,    0,   13,
       14,    0,   32,   39,    0,    6,    0,  187,   41,   28,

       30,   21,   45,   33,   31,   29,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   86,
        0,    0,    0,    0,  172,    0,  173,    0,    0,    0,
      175,    0,    0,    0,   85,    0,    0,    0,    0,    0,
        0,    0,    0,  174,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   62,    0,    0,    0,    0,
        0,  125,    0,    0,    0,    0,  143,    0,    0,  144,
        0,    0,   35,    0,    0,  146,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,  268,    0,
        0,    0,    0,    0,  145,    0,   18,   22,   23,    9,
        7,    8,   10,   12,    0,   40,   48,  187,   42,   37,
       47,   43,   46,    0,    0,    0,  255,  181,    0,    0,
      252,    0,    0,    0,  167,    0,    0,   50,  258,    0,
        0,    0,    0,    0,    0,  180,    0,    0,  182,    0,
      176,    0,    0,  240,  178,    0,    0,    0,    0,    0,
        0,    0,    0,   58,    0,   34,    0,    0,    0,    5,
        0,  238,    0,   72,    0,    0,  152,    0,    0,   88,
       90,   92,   69,    0,    0,    0,  131,  234,    0,    0,

      138,    0,  123,    0,    0,    0,    0,  129,    0,  236,
        0,    0,   49,  257,    0,    0,    0,  130,  256,  124,
      127,  128,  204,    0,   36,    0,    0,    0,  151,    0,
      153,  147,    0,    0,   91,  126,    0,   87,    0,    0,
        0,  239,    0,   89,  149,    0,    0,    0,    0,  237,
        0,    0,    0,    0,   38,   44,    0,    0,  162,    0,
       81,    0,    0,   75,    0,   82,    0,    0,  169,    0,
        0,   76,  262,    0,  244,   78,   79,   80,    0,    0,
        0,    0,    0,  166,   77,   95,   99,  103,    0,    0,
        0,    0,    0,  101,   93,   97,    0,    0,  226,  231,

      133,  208,  206,    0,    0,  106,  108,  110,  235,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  267,    0,
       56,    0,    0,  210,  215,    0,  265,    0,    0,    0,
      140,    0,    0,    0,    0,    0,  261,    0,    0,   54,
      243,    0,  202,    0,  109,    0,  105,  203,   17,    0,
        0,    0,    0,  107,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  218,  223,  269,    0,  137,   11,
        0,   84,  161,    0,  164,    0,  163,    0,    0,    0,
      170,    0,    0,  183,    0,  177,    0,  168,  251,    0,
      113,  117,  121,   83,  132,    0,    0,    0,    0,    0,

      119,  111,  115,  227,  232,    0,    0,    0,  209,    0,
        0,    0,  135,  195,   74,    0,    0,  205,    0,    0,
      134,  211,  216,    0,    0,    0,  266,    0,   51,    0,
        0,  141,    0,   57,    0,   63,    0,  154,    0,    0,
        0,    0,  207,  148,    0,    0,    0,    0,  139,   68,
        0,    0,    0,  157,    0,    0,    0,  219,  224,    0,
        0,    0,  270,  187,  248,    0,    0,    0,    0,  171,
        0,    0,    0,    0,   96,  100,  104,  102,   94,   98,
        0,  228,  233,    0,  201,  247,   16,    0,   61,    0,
       59,    0,  212,  217,    0,    0,    0,    0,  142,   64,

        0,    0,    0,    0,   24,   65,    0,    0,   66,    0,
        0,  160,  158,    0,    0,    0,  220,  225,    0,    0,
      165,    0,    0,    0,    0,  246,    0,  179,  114,  118,
      122,  120,  112,  116,    0,  229,    0,  136,   60,    0,
      213,    0,    0,    0,    0,    0,   55,  245,    0,    0,
      150,    0,    0,    0,    0,  221,    0,   53,  260,    0,
        0,  242,  230,    0,  214,   52,  259,    0,    0,    0,
      241,   67,    0,  159,  156,  222,  250,  253,  264,  249,
       70,  263,    0,    0,    0,    0,    0,  155,    0,    0,
        0,  254,   71,    0,  196,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,    9,    8,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    8,   19,   20,
       21,   22,    8,    8,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   28,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   28,   28,   43,   28,   44,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,   77,   78,   79,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[80] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[698] =
    {   0,
        0,  656,  700,  702,  654,  702,  677,  691,  702,  702,
      702,   68,  702,  702,  681,  702,   73,  679,  677,   71,
      702,   76,   77,   79,  632,  638,   52,  637,   38,  702,
      640,  621,   48,  638,  637,  616,   22,   46,   56,  617,
       71,   47,   69,   64,  626,   67,  702,  702,  702,  702,
      702,   79,   80,   87,   79,   87,   97,   86,  633,  104,
      632,  113,  116,  109,  120,  131,  126,  137,  144,  107,
      100,  624,  622,  625,  702,  601,  702,  148,  702,  702,
      702,  671,  702,  665,  664,  663,  662,  661,  603,  702,
      702,  648,  702,  702,  653,  702,  650,  184,  170,  702,

      175,  645,  702,  702,  702,  702,  150,  597,  600,  606,
      598,  608,  596,  599,  591,  604,  607,  594,  601,  702,
      150,  585,  588,  590,  702,  597,  702,  587,  595,  590,
      702,  583,  155,  592,  702,  581,  590,  587,  580,  571,
      586,  581,  570,  702,  568,  582,  146,  157,  582,  582,
      162,  583,  565,  562,  156,  572,  159,  160,  577,  563,
      563,  174,  557,  560,  556,  573,  168,  558,  554,  556,
      557,  565,  567,  547,  174,  179,  546,  549,  551,  550,
      549,  702,  554,  536,  545,  554,  702,  555,  536,  702,
      541,  549,  702,  535,  543,  702,  536,  541,  534,  172,

      545,  533,  182,  528,  544,  188,  177,  539,  702,  534,
      523,  523,  537,  534,  702,  518,  702,  702,  702,  702,
      702,  702,  702,  702,  517,  702,  702,  228,  563,  702,
      562,  702,  702,  518,  525,  531,  702,  702,  513,  510,
      702,  509,  519,  507,  702,  513,  505,  515,  518,  521,
      505,  518,  499,  498,  510,  702,  512,  495,  702,  494,
      702,  493,  499,  510,  702,  490,  494,  499,  506,  486,
      183,  502,  488,  702,  495,  702,  189,  499,  487,  702,
      486,  245,  498,  702,  493,  485,  702,  481,  477,  486,
      485,  484,  702,  471,  472,  469,  533,  702,  467,  477,

      702,  466,  702,  469,  250,  470,  469,  702,  477,  252,
      466,  459,  201,  473,  476,  460,  473,  702,  702,  702,
      702,  702,  702,  462,  208,  453,  465,  206,  702,  208,
      702,  702,  451,  456,  461,  702,  455,  459,  446,  447,
      445,  462,  209,  454,  702,  441,  445,  450,  211,  264,
      204,  457,  495,  489,  702,  702,  447,  453,  702,  438,
      702,  451,  439,  702,  449,  702,  435,  216,  702,  447,
      443,  702,  441,  444,  423,  702,  702,  702,  442,  422,
      440,  426,  427,  702,  702,  430,  429,  428,  427,  433,
      217,  228,  432,  424,  423,  422,  229,  231,  414,  702,

      702,  409,  702,  408,  411,  702,  702,  702,  702,  420,
      423,  427,  397,  409,  400,  401,  417,  405,  702,  415,
      702,  233,  235,  400,  702,  394,  702,  399,  387,  228,
      702,  410,  406,  408,  399,  393,  401,  404,  390,  394,
      381,  381,  702,  396,  702,  398,  702,  702,  702,  393,
      377,  378,  390,  702,  393,  379,  380,  375,  239,  382,
      380,  380,  240,  243,  372,  702,  702,  381,  702,  702,
      418,  702,  702,  380,  702,  368,  702,  373,  363,  361,
      702,  378,  371,  702,  374,  702,  367,  702,  702,  360,
      702,  702,  702,  702,  702,  237,  371,  370,  358,  357,

      702,  702,  702,  355,  702,  407,  406,  347,  702,  361,
      361,  359,  702,  702,  702,  348,  343,  702,  349,  348,
      702,  344,  702,  396,  395,  336,  702,  346,  702,  336,
      334,  702,  351,  702,  337,  702,  343,  702,  329,  347,
      344,  331,  702,  702,  325,  335,  324,  322,  702,  702,
      326,  321,  330,  702,  323,  330,  331,  320,  702,  372,
      371,  312,  702,  702,  310,  316,  309,  327,  322,  702,
      308,  305,  309,  309,  314,  313,  312,  311,  310,  309,
      296,  702,  702,  314,  702,  293,  702,  299,  702,  300,
      702,  291,  702,  702,  309,  289,  307,  302,  702,  702,

      288,  297,  292,  283,  702,  702,  287,  296,  702,  286,
      290,  702,  702,  285,  277,  276,  702,  702,  294,  291,
      702,  268,  280,  288,  289,  702,  275,  702,  702,  702,
      702,  702,  702,  702,  287,  702,  284,  702,  702,  285,
      702,  260,  272,  280,  281,  276,  702,  702,  266,  259,
      702,  266,  276,  275,  274,  702,  252,  702,  702,  251,
      258,  702,  702,  249,  702,  702,  702,  248,  255,  247,
      702,  702,  250,  702,  702,  702,  702,  255,  702,  702,
      254,  702,  255,  245,  243,  205,  196,  702,  121,  112,
      141,  702,  702,   70,  702,  702,   81

    } ;

static yyconst flex_int16_t yy_def[698] =
    {   0,
      696,    1,  696,  696,  696,  696,  696,  697,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  697,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,

      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,

      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,

      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,

      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,

      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,

      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,    0,  696

    } ;

static yyconst flex_int16_t yy_nxt[782] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   30,   61,
       62,   63,   64,   65,   66,   30,   67,   68,   69,   70,
       71,   72,   73,   30,   74,   75,   76,   77,   78,   84,
       85,   82,   86,   87,   88,   91,   97,   92,   98,  126,
       99,  127,   93,  104,   94,  100,  101,  102,  103,  105,

      106,  109,  115,  128,  138,  116,  117,  129,  110,  120,
      121,  122,  130,  131,  695,  111,  139,   89,  140,  112,
      145,  113,  132,  133,  135,  141,  142,  136,  143,  153,
      147,  161,  162,  154,  146,  171,  155,  172,  137,  148,
      156,  149,  163,  157,  694,  150,  151,  152,  164,  212,
      158,  165,  173,  213,  159,  166,  160,  168,  188,  167,
      169,  175,  179,  170,  180,  184,  176,  177,  218,  210,
      181,  211,  189,  185,  693,  182,  183,  191,  190,  186,
      194,  192,  199,  692,  229,  187,  193,  195,  196,  200,
      201,  230,  202,  207,  203,  231,  232,  197,  198,   97,

      208,   98,  204,  234,  248,  205,  206,  209,  258,  271,
      273,  435,  259,  272,  235,  278,  287,  274,  249,  279,
      284,  275,  288,  285,  289,  302,  219,  290,  291,  295,
      280,  311,  303,  313,  296,  333,  312,  337,  341,  344,
      391,  334,  297,  354,  338,  228,  345,  314,  397,  342,
      386,  387,  343,  417,  398,  422,  392,  393,  428,  439,
      441,  423,  452,  691,  458,  436,  467,  463,  690,  429,
      468,  479,  442,  464,  440,  459,  453,  460,  461,  462,
      496,  498,  480,  530,  497,  499,  504,  505,  506,  507,
      522,  523,  524,  525,  531,  553,  554,  558,  559,  418,

      560,  561,  399,  400,  575,  576,  689,  688,  687,  424,
      425,  686,  685,  684,  683,  682,  681,  680,  679,  678,
      677,  465,  466,  676,  675,  674,  673,  672,  671,  670,
      669,  668,  667,  666,  665,  664,  663,  662,  661,  660,
      659,  658,  657,  656,  655,  654,  653,  652,  651,  650,
      649,  648,  647,  646,  645,  644,  643,  642,  641,  640,
      639,  638,  637,  636,  635,  634,  633,  632,  631,  630,
      629,  628,  627,  626,  625,  624,  623,  622,  621,  620,
      619,  618,  617,  616,  615,  614,  613,  612,  611,  610,
      609,  608,  607,  606,  605,  604,  603,  602,  601,  600,

      599,  598,  597,  596,  595,  594,  593,  592,  591,  590,
      589,  588,  587,  586,  585,  584,  583,  582,  581,  580,
      579,  578,  577,  574,  573,  572,  571,  570,  569,  568,
      567,  566,  565,  564,  563,  562,  557,  556,  555,  552,
      551,  550,  549,  548,  547,  546,  545,  544,  543,  542,
      541,  540,  539,  538,  537,  536,  535,  534,  533,  532,
      529,  528,  527,  526,  521,  520,  519,  518,  517,  516,
      515,  514,  513,  512,  511,  510,  509,  508,  503,  502,
      501,  500,  495,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  483,  482,  481,  478,  477,  476,

      475,  474,  473,  472,  471,  470,  469,  457,  456,  455,
      454,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      438,  437,  434,  433,  432,  431,  430,  427,  426,  421,
      420,  419,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  396,  395,
      394,  390,  389,  388,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  353,  352,  351,  350,  349,
      348,  347,  346,  340,  339,  336,  335,  332,  331,  330,

      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  310,  309,  308,  307,  306,
      305,  304,  301,  300,  299,  298,  294,  293,  292,  286,
      283,  282,  281,  277,  276,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  257,  256,  255,  254,
      253,  252,  251,  250,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  233,  228,  227,  226,
      225,  224,  223,  222,  221,  220,   83,  217,  216,  215,
      214,  178,  174,  144,  134,  125,  124,  123,  119,  118,
      114,  108,  107,   96,   95,   90,   83,   81,   80,  696,

       79,    3,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696
    } ;

static yyconst flex_int16_t yy_chk[782] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
       12,  697,   12,   12,   12,   17,   20,   17,   20,   37,
       22,   37,   17,   24,   17,   22,   22,   23,   23,   24,

       24,   27,   29,   38,   42,   29,   29,   38,   27,   33,
       33,   33,   39,   39,  694,   27,   42,   12,   43,   27,
       46,   27,   39,   39,   41,   43,   44,   41,   44,   53,
       52,   55,   55,   53,   46,   58,   54,   58,   41,   52,
       54,   52,   55,   54,  691,   52,   52,   52,   56,   71,
       54,   56,   58,   71,   54,   56,   54,   57,   64,   56,
       57,   60,   62,   57,   62,   63,   60,   60,   78,   70,
       62,   70,   64,   63,  690,   62,   62,   65,   64,   63,
       66,   65,   67,  689,   99,   63,   65,   66,   66,   67,
       68,   99,   68,   69,   68,  101,  101,   66,   66,   98,

       69,   98,   68,  107,  121,   68,   68,   69,  133,  147,
      148,  325,  133,  147,  107,  151,  157,  148,  121,  151,
      155,  148,  157,  155,  158,  167,   78,  158,  158,  162,
      151,  175,  167,  176,  162,  200,  175,  203,  206,  207,
      277,  200,  162,  228,  203,  228,  207,  176,  282,  206,
      271,  271,  206,  305,  282,  310,  277,  277,  313,  328,
      330,  310,  343,  687,  349,  325,  351,  350,  686,  313,
      351,  368,  330,  350,  328,  349,  343,  349,  349,  349,
      391,  392,  368,  430,  391,  392,  397,  397,  398,  398,
      422,  422,  423,  423,  430,  459,  459,  463,  463,  305,

      464,  464,  282,  282,  496,  496,  685,  684,  683,  310,
      310,  681,  678,  673,  670,  669,  668,  664,  661,  660,
      657,  350,  350,  655,  654,  653,  652,  650,  649,  646,
      645,  644,  643,  642,  640,  637,  635,  627,  625,  624,
      623,  622,  620,  619,  616,  615,  614,  611,  610,  608,
      607,  604,  603,  602,  601,  598,  597,  596,  595,  592,
      590,  588,  586,  584,  581,  580,  579,  578,  577,  576,
      575,  574,  573,  572,  571,  569,  568,  567,  566,  565,
      562,  561,  560,  558,  557,  556,  555,  553,  552,  551,
      548,  547,  546,  545,  542,  541,  540,  539,  537,  535,

      533,  531,  530,  528,  526,  525,  524,  522,  520,  519,
      517,  516,  512,  511,  510,  508,  507,  506,  504,  500,
      499,  498,  497,  490,  487,  485,  483,  482,  480,  479,
      478,  476,  474,  471,  468,  465,  462,  461,  460,  458,
      457,  456,  455,  453,  452,  451,  450,  446,  444,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      429,  428,  426,  424,  420,  418,  417,  416,  415,  414,
      413,  412,  411,  410,  405,  404,  402,  399,  396,  395,
      394,  393,  390,  389,  388,  387,  386,  383,  382,  381,
      380,  379,  375,  374,  373,  371,  370,  367,  365,  363,

      362,  360,  358,  357,  354,  353,  352,  348,  347,  346,
      344,  342,  341,  340,  339,  338,  337,  335,  334,  333,
      327,  326,  324,  317,  316,  315,  314,  312,  311,  309,
      307,  306,  304,  302,  300,  299,  297,  296,  295,  294,
      292,  291,  290,  289,  288,  286,  285,  283,  281,  279,
      278,  275,  273,  272,  270,  269,  268,  267,  266,  264,
      263,  262,  260,  258,  257,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  244,  243,  242,  240,  239,
      236,  235,  234,  231,  229,  225,  216,  214,  213,  212,
      211,  210,  208,  205,  204,  202,  201,  199,  198,  197,

      195,  194,  192,  191,  189,  188,  186,  185,  184,  183,
      181,  180,  179,  178,  177,  174,  173,  172,  171,  170,
      169,  168,  166,  165,  164,  163,  161,  160,  159,  156,
      154,  153,  152,  150,  149,  146,  145,  143,  142,  141,
      140,  139,  138,  137,  136,  134,  132,  130,  129,  128,
      126,  124,  123,  122,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  102,   97,   95,   92,
       89,   88,   87,   86,   85,   84,   82,   76,   74,   73,
       72,   61,   59,   45,   40,   36,   35,   34,   32,   31,
       28,   26,   25,   19,   18,   15,    8,    7,    5,    3,

        2,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696,  696,  696,  696,  696,  696,  696,  696,  696,  696,
      696
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "math.l"
#line 2 "math.l"
#include "math.tab.h"
#line 865 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 5 "math.l"


#line 1058 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 697 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 702 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "math.l"
{ yylval = 0; return SOPT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "math.l"
{ yylval = 1; return SOPT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "math.l"
{ yylval = 2; return SOPT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "math.l"
{ yylval = 3; return SOPT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "math.l"
{ yylval = 4; return SOPT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "math.l"
{ yylval = 5; return SOPT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "math.l"
{ yylval = 6; return SOPT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 15 "math.l"
{ yylval = 7; return SOPT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "math.l"
{ yylval = 8; return SOPT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "math.l"
{ yylval = 9; return SOPT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 18 "math.l"
{ yylval = 10; return SOPT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 19 "math.l"
{ yylval = 11; return SOPT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "math.l"
{ yylval = 12; return SOPT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "math.l"
{ yylval = 13; return SOPT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 24 "math.l"
{ yylval = 14; return SOPT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "math.l"
{ yylval = 15; return SOPT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 26 "math.l"
{ yylval = 16; return SOPT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "math.l"
{ yylval = 17; return SOPT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "math.l"
{ yylval = 18; return SOPT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "math.l"
{ yylval = 0; return SEQV; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "math.l"
{ yylval = 1; return SEQV; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "math.l"
{ yylval = 2; return SEQV; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "math.l"
{ yylval = 3; return SEQV; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "math.l"
{ yylval = 4; return SEQV; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "math.l"
{ yylval = 5; return SEQV; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "math.l"
{ yylval = 6; return SEQV; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "math.l"
{ yylval = 7; return SEQV; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "math.l"
{ yylval = 8; return SEQV; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 40 "math.l"
{ yylval = 9; return SEQV; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 41 "math.l"
{ yylval = 10; return SEQV; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 42 "math.l"
{ yylval = 11; return SEQV; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 43 "math.l"
{ yylval = 12; return SEQV; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 44 "math.l"
{ yylval = 13; return SEQV; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "math.l"
{ yylval = 0; return SLGC; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "math.l"
{ yylval = 1; return SLGC; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "math.l"
{ yylval = 2; return SLGC; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "math.l"
{ yylval = 3; return SLGC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "math.l"
{ yylval = 4; return SLGC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "math.l"
{ yylval = 5; return SLGC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "math.l"
{ yylval = 6; return SLGC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "math.l"
{ yylval = 7; return SLGC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "math.l"
{ yylval = 8; return SLGC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "math.l"
{ yylval = 9; return SLGC; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "math.l"
{ yylval = 10; return SLGC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "math.l"
{ yylval = 11; return SLGC; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "math.l"
{ yylval = 12; return SLGC; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "math.l"
{ yylval = 13; return SLGC; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "math.l"
{ yylval = 0; return SOTH; }
	YY_BREAK
case 49:
#line 65 "math.l"
case 50:
#line 66 "math.l"
case 51:
#line 67 "math.l"
case 52:
#line 68 "math.l"
case 53:
YY_RULE_SETUP
#line 68 "math.l"
{ yylval = 1; return SOTH; }
	YY_BREAK
case 54:
#line 71 "math.l"
case 55:
YY_RULE_SETUP
#line 71 "math.l"
{ yylval = 2; return SOTH; }
	YY_BREAK
case 56:
#line 73 "math.l"
case 57:
YY_RULE_SETUP
#line 73 "math.l"
{ yylval = 3; return SOTH; }
	YY_BREAK
case 58:
#line 77 "math.l"
case 59:
#line 78 "math.l"
case 60:
YY_RULE_SETUP
#line 78 "math.l"
{ yylval = 0; return SSET; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 79 "math.l"
{ yylval = 1; return SSET; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 "math.l"
{ yylval = 2; return SSET; }
	YY_BREAK
case 63:
#line 83 "math.l"
case 64:
YY_RULE_SETUP
#line 83 "math.l"
{ yylval = 3; return SSET; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 84 "math.l"
{ yylval = 4; return SSET; }
	YY_BREAK
case 66:
#line 86 "math.l"
case 67:
YY_RULE_SETUP
#line 86 "math.l"
{ yylval = 5; return SSET; }
	YY_BREAK
case 68:
#line 89 "math.l"
case 69:
YY_RULE_SETUP
#line 89 "math.l"
{ yylval = 6; return SSET; }
	YY_BREAK
case 70:
#line 91 "math.l"
case 71:
#line 92 "math.l"
case 72:
YY_RULE_SETUP
#line 92 "math.l"
{ yylval = 7; return SSET; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 93 "math.l"
{ yylval = 8; return SSET; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 96 "math.l"
{ yylval = 0; return NSET; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 97 "math.l"
{ yylval = 1; return NSET; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 98 "math.l"
{ yylval = 2; return NSET; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 99 "math.l"
{ yylval = 3; return NSET; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 100 "math.l"
{ yylval = 4; return NSET; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 101 "math.l"
{ yylval = 5; return NSET; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 102 "math.l"
{ yylval = 6; return NSET; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 103 "math.l"
{ yylval = 7; return NSET; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 104 "math.l"
{ yylval = 8; return NSET; }
	YY_BREAK
case 83:
#line 106 "math.l"
case 84:
YY_RULE_SETUP
#line 106 "math.l"
{ yylval = 9; return NSET; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "math.l"
{ yylval = 10; return NSET; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 108 "math.l"
{ yylval = 11; return NSET; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 111 "math.l"
{ yylval = 0; return NTRI; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 112 "math.l"
{ yylval = 1; return NTRI; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 113 "math.l"
{ yylval = 2; return NTRI; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 114 "math.l"
{ yylval = 3; return NTRI; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 115 "math.l"
{ yylval = 4; return NTRI; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 116 "math.l"
{ yylval = 5; return NTRI; }
	YY_BREAK
case 93:
#line 118 "math.l"
case 94:
YY_RULE_SETUP
#line 118 "math.l"
{ yylval = 6; return NTRI; }
	YY_BREAK
case 95:
#line 120 "math.l"
case 96:
YY_RULE_SETUP
#line 120 "math.l"
{ yylval = 7; return NTRI; }
	YY_BREAK
case 97:
#line 122 "math.l"
case 98:
YY_RULE_SETUP
#line 122 "math.l"
{ yylval = 8; return NTRI; }
	YY_BREAK
case 99:
#line 124 "math.l"
case 100:
YY_RULE_SETUP
#line 124 "math.l"
{ yylval = 9; return NTRI; }
	YY_BREAK
case 101:
#line 126 "math.l"
case 102:
YY_RULE_SETUP
#line 126 "math.l"
{ yylval = 10; return NTRI; }
	YY_BREAK
case 103:
#line 128 "math.l"
case 104:
YY_RULE_SETUP
#line 128 "math.l"
{ yylval = 11; return NTRI; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 130 "math.l"
{ yylval = 0; return NHYB; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 131 "math.l"
{ yylval = 1; return NHYB; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 132 "math.l"
{ yylval = 2; return NHYB; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 133 "math.l"
{ yylval = 3; return NHYB; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 134 "math.l"
{ yylval = 4; return NHYB; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 135 "math.l"
{ yylval = 5; return NHYB; }
	YY_BREAK
case 111:
#line 137 "math.l"
case 112:
YY_RULE_SETUP
#line 137 "math.l"
{ yylval = 6; return NHYB; }
	YY_BREAK
case 113:
#line 139 "math.l"
case 114:
YY_RULE_SETUP
#line 139 "math.l"
{ yylval = 7; return NHYB; }
	YY_BREAK
case 115:
#line 141 "math.l"
case 116:
YY_RULE_SETUP
#line 141 "math.l"
{ yylval = 8; return NHYB; }
	YY_BREAK
case 117:
#line 143 "math.l"
case 118:
YY_RULE_SETUP
#line 143 "math.l"
{ yylval = 9; return NHYB; }
	YY_BREAK
case 119:
#line 145 "math.l"
case 120:
YY_RULE_SETUP
#line 145 "math.l"
{ yylval = 10; return NHYB; }
	YY_BREAK
case 121:
#line 147 "math.l"
case 122:
YY_RULE_SETUP
#line 147 "math.l"
{ yylval = 11; return NHYB; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 150 "math.l"
{ yylval = 0; return NEXP; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 151 "math.l"
{ yylval = 1; return NEXP; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 152 "math.l"
{ yylval = 2; return NEXP; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 155 "math.l"
{ yylval = 0; return NOTH; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 156 "math.l"
{ yylval = 1; return NOTH; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 157 "math.l"
{ yylval = 2; return NOTH; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 158 "math.l"
{ yylval = 3; return NOTH; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 159 "math.l"
{ yylval = 4; return NOTH; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 160 "math.l"
{ yylval = 5; return NOTH; }
	YY_BREAK
case 132:
#line 165 "math.l"
case 133:
#line 166 "math.l"
case 134:
#line 167 "math.l"
case 135:
#line 168 "math.l"
case 136:
#line 169 "math.l"
case 137:
#line 170 "math.l"
case 138:
#line 171 "math.l"
case 139:
#line 172 "math.l"
case 140:
#line 173 "math.l"
case 141:
#line 174 "math.l"
case 142:
#line 175 "math.l"
case 143:
#line 176 "math.l"
case 144:
#line 177 "math.l"
case 145:
#line 178 "math.l"
case 146:
#line 179 "math.l"
case 147:
#line 180 "math.l"
case 148:
#line 181 "math.l"
case 149:
#line 182 "math.l"
case 150:
#line 183 "math.l"
case 151:
#line 184 "math.l"
case 152:
#line 185 "math.l"
case 153:
#line 186 "math.l"
case 154:
YY_RULE_SETUP
#line 186 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 155:
#line 189 "math.l"
case 156:
#line 190 "math.l"
case 157:
#line 191 "math.l"
case 158:
#line 192 "math.l"
case 159:
#line 193 "math.l"
case 160:
YY_RULE_SETUP
#line 193 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 161:
#line 196 "math.l"
case 162:
#line 197 "math.l"
case 163:
#line 198 "math.l"
case 164:
#line 199 "math.l"
case 165:
#line 200 "math.l"
case 166:
#line 201 "math.l"
case 167:
#line 202 "math.l"
case 168:
#line 203 "math.l"
case 169:
#line 204 "math.l"
case 170:
#line 205 "math.l"
case 171:
#line 206 "math.l"
case 172:
#line 207 "math.l"
case 173:
#line 208 "math.l"
case 174:
#line 209 "math.l"
case 175:
#line 210 "math.l"
case 176:
#line 211 "math.l"
case 177:
#line 212 "math.l"
case 178:
#line 213 "math.l"
case 179:
#line 214 "math.l"
case 180:
#line 215 "math.l"
case 181:
#line 216 "math.l"
case 182:
#line 217 "math.l"
case 183:
YY_RULE_SETUP
#line 217 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 219 "math.l"
{ yylval = (int)yytext; return ENGL; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 220 "math.l"
{ yylval = (int)yytext; return PUNCT; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 221 "math.l"
{ yylval = (int)yytext; return ESCCH; }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 223 "math.l"
{ yylval = (int)yytext; return NUMBER; }
	YY_BREAK
case 188:
/* rule 188 can match eol */
YY_RULE_SETUP
#line 225 "math.l"
{ yylval = (int)yytext; return TEXT; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 229 "math.l"
{ return OP; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 230 "math.l"
{ return CP; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 232 "math.l"
{ return OS; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 233 "math.l"
{ return CS; }
	YY_BREAK
case 193:
#line 236 "math.l"
case 194:
YY_RULE_SETUP
#line 236 "math.l"
{ return OB_M; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 237 "math.l"
{ return OB_D; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 238 "math.l"
{ return OB_P; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 239 "math.l"
{ return OB; }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 240 "math.l"
{ return CB; }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 244 "math.l"
{ return DIV; }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 245 "math.l"
{ return POW; }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 246 "math.l"
{ return CHS; }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 247 "math.l"
{ return NRT; }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 248 "math.l"
{ return SRT; }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 250 "math.l"
{ return MOD; }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 251 "math.l"
{ return FLR; }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 252 "math.l"
{ return CIL; }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 253 "math.l"
{ return RND; }
	YY_BREAK
case 208:
#line 256 "math.l"
case 209:
YY_RULE_SETUP
#line 256 "math.l"
{ return SWC; }
	YY_BREAK
case 210:
#line 260 "math.l"
case 211:
#line 261 "math.l"
case 212:
YY_RULE_SETUP
#line 261 "math.l"
{ yylval = 0; return NOVR; }
	YY_BREAK
case 213:
#line 263 "math.l"
case 214:
YY_RULE_SETUP
#line 263 "math.l"
{ yylval = 1; return NOVR; }
	YY_BREAK
case 215:
#line 265 "math.l"
case 216:
#line 266 "math.l"
case 217:
YY_RULE_SETUP
#line 266 "math.l"
{ yylval = 2; return NOVR; }
	YY_BREAK
case 218:
#line 268 "math.l"
case 219:
#line 269 "math.l"
case 220:
YY_RULE_SETUP
#line 269 "math.l"
{ yylval = 3; return NOVR; }
	YY_BREAK
case 221:
#line 271 "math.l"
case 222:
YY_RULE_SETUP
#line 271 "math.l"
{ yylval = 4; return NOVR; }
	YY_BREAK
case 223:
#line 273 "math.l"
case 224:
#line 274 "math.l"
case 225:
YY_RULE_SETUP
#line 274 "math.l"
{ yylval = 5; return NOVR; }
	YY_BREAK
case 226:
#line 276 "math.l"
case 227:
#line 277 "math.l"
case 228:
YY_RULE_SETUP
#line 277 "math.l"
{ yylval = 6; return NOVR; }
	YY_BREAK
case 229:
#line 279 "math.l"
case 230:
YY_RULE_SETUP
#line 279 "math.l"
{ yylval = 7; return NOVR; }
	YY_BREAK
case 231:
#line 281 "math.l"
case 232:
#line 282 "math.l"
case 233:
YY_RULE_SETUP
#line 282 "math.l"
{ yylval = 8; return NOVR; }
	YY_BREAK
case 234:
YY_RULE_SETUP
#line 285 "math.l"
{ yylval = 0; return OOVR; }
	YY_BREAK
case 235:
YY_RULE_SETUP
#line 286 "math.l"
{ yylval = 1; return OOVR; }
	YY_BREAK
case 236:
YY_RULE_SETUP
#line 287 "math.l"
{ yylval = 2; return OOVR; }
	YY_BREAK
case 237:
YY_RULE_SETUP
#line 288 "math.l"
{ yylval = 3; return OOVR; }
	YY_BREAK
case 238:
YY_RULE_SETUP
#line 289 "math.l"
{ yylval = 4; return OOVR; }
	YY_BREAK
case 239:
#line 293 "math.l"
case 240:
#line 294 "math.l"
case 241:
#line 295 "math.l"
case 242:
YY_RULE_SETUP
#line 295 "math.l"
{ yylval = 0; return OSUM; }
	YY_BREAK
case 243:
#line 298 "math.l"
case 244:
#line 299 "math.l"
case 245:
#line 300 "math.l"
case 246:
YY_RULE_SETUP
#line 300 "math.l"
{ yylval = 1; return OSUM; }
	YY_BREAK
case 247:
#line 303 "math.l"
case 248:
#line 304 "math.l"
case 249:
#line 305 "math.l"
case 250:
YY_RULE_SETUP
#line 305 "math.l"
{ yylval = 2; return OSUM; }
	YY_BREAK
case 251:
#line 308 "math.l"
case 252:
YY_RULE_SETUP
#line 308 "math.l"
{ yylval = 3; return OSUM; }
	YY_BREAK
case 253:
#line 310 "math.l"
case 254:
#line 311 "math.l"
case 255:
YY_RULE_SETUP
#line 311 "math.l"
{ yylval = 4; return OSUM; }
	YY_BREAK
case 256:
YY_RULE_SETUP
#line 313 "math.l"
{ yylval = 5; return OSUM; }
	YY_BREAK
case 257:
#line 316 "math.l"
case 258:
#line 317 "math.l"
case 259:
#line 318 "math.l"
case 260:
YY_RULE_SETUP
#line 318 "math.l"
{ yylval = 6; return OSUM; }
	YY_BREAK
case 261:
#line 321 "math.l"
case 262:
#line 322 "math.l"
case 263:
#line 323 "math.l"
case 264:
YY_RULE_SETUP
#line 323 "math.l"
{ yylval = 7; return OSUM; }
	YY_BREAK
case 265:
YY_RULE_SETUP
#line 325 "math.l"
{ yylval = 8; return OSUM; }
	YY_BREAK
case 266:
YY_RULE_SETUP
#line 326 "math.l"
{ yylval = 9; return OSUM; }
	YY_BREAK
case 267:
YY_RULE_SETUP
#line 329 "math.l"
{ return FR; }
	YY_BREAK
case 268:
YY_RULE_SETUP
#line 330 "math.l"
{ return TO; }
	YY_BREAK
case 269:
#line 332 "math.l"
case 270:
YY_RULE_SETUP
#line 332 "math.l"
{ return WH; }
	YY_BREAK
case 271:
YY_RULE_SETUP
#line 335 "math.l"
{ return SPC; }
	YY_BREAK
case 272:
YY_RULE_SETUP
#line 336 "math.l"
{ return SEP; }
	YY_BREAK
case 273:
YY_RULE_SETUP
#line 337 "math.l"
{ return SNL; }
	YY_BREAK
case 274:
YY_RULE_SETUP
#line 338 "math.l"
{ return ALG; }
	YY_BREAK
case 275:
/* rule 275 can match eol */
YY_RULE_SETUP
#line 339 "math.l"
{ return EOL; }
	YY_BREAK
case 276:
YY_RULE_SETUP
#line 340 "math.l"
{ /* do nothing */ }
	YY_BREAK
case 277:
YY_RULE_SETUP
#line 341 "math.l"
{ printf("Unknown: %c\n", *yytext); }
	YY_BREAK
case 278:
YY_RULE_SETUP
#line 343 "math.l"
ECHO;
	YY_BREAK
#line 2201 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 697 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 697 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 696);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 343 "math.l"



