
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 259
#define YY_END_OF_BUFFER 260
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[643] =
    {   0,
        0,    0,  260,  258,  257,  256,  176,  258,  177,  176,
      180,  181,    3,    1,  254,    2,    4,  190,  178,  255,
       24,   18,   25,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  186,   65,  187,  191,  253,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  182,  258,  183,   15,  184,  185,   23,
        0,  179,    0,    0,    0,    0,    0,    0,   13,   14,
       30,   33,    0,    6,    0,  178,   32,   26,   28,   19,

       35,   31,   29,   27,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   77,    0,    0,
        0,    0,  163,    0,  164,    0,    0,  166,    0,    0,
        0,   76,    0,    0,    0,    0,    0,    0,    0,    0,
      165,    0,    0,  189,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   54,    0,    0,    0,    0,    0,  116,    0,
        0,    0,    0,  134,    0,    0,  135,    0,    0,   38,
        0,    0,  137,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,  250,    0,    0,    0,    0,
        0,  136,    0,  188,   20,   21,    9,    7,    8,   10,
       12,    0,   40,  178,   34,   36,    0,    0,    0,  240,
      172,    0,    0,  237,    0,    0,    0,  158,    0,    0,
       42,  243,    0,    0,    0,    0,    0,  171,    0,    0,
      173,    0,  167,    0,    0,  225,  169,    0,    0,    0,
        0,    0,    0,    0,    0,   50,    0,   37,    0,    0,
        0,    5,    0,  223,    0,   64,    0,    0,  143,    0,
        0,   79,   81,   83,   61,    0,    0,    0,  122,  219,
        0,  129,    0,  114,    0,    0,    0,    0,  120,    0,

      221,    0,    0,   41,  242,    0,    0,    0,  121,  241,
      115,  118,  119,  195,    0,   39,    0,    0,    0,  142,
        0,  144,  138,    0,    0,   82,  117,    0,   78,    0,
        0,    0,  224,    0,   80,  140,    0,    0,    0,    0,
      222,    0,    0,    0,    0,    0,    0,  153,    0,   72,
        0,    0,   66,    0,   73,    0,    0,  160,    0,    0,
       67,    0,  229,   69,   70,   71,    0,    0,    0,    0,
        0,  157,   68,   86,   90,   94,    0,    0,    0,    0,
        0,   92,   84,   88,    0,    0,  213,  216,  124,  199,
      197,    0,    0,   97,   99,  101,  220,    0,    0,    0,

        0,    0,    0,    0,  249,    0,   48,    0,    0,  201,
      204,    0,  247,    0,    0,    0,  131,    0,    0,    0,
        0,    0,  246,    0,   46,  228,    0,  193,    0,  100,
        0,   96,  194,   17,    0,    0,    0,    0,   98,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  207,
      210,  251,    0,  128,   11,    0,   75,  152,    0,  155,
        0,  154,    0,    0,    0,  161,    0,  174,    0,  168,
        0,  159,  236,    0,  104,  108,  112,   74,  123,    0,
        0,    0,    0,    0,  110,  102,  106,  214,  217,    0,
        0,  200,    0,    0,    0,  126,    0,    0,  196,    0,

        0,  125,  202,  205,    0,    0,  248,    0,   43,    0,
        0,  132,    0,   49,    0,   55,  145,    0,    0,    0,
      198,  139,    0,    0,    0,    0,  130,   60,    0,    0,
        0,  148,    0,    0,    0,  208,  211,    0,    0,  252,
      178,  233,    0,    0,    0,    0,  162,    0,    0,    0,
       87,   91,   95,   93,   85,   89,  215,  218,  192,  232,
       16,    0,   53,    0,   51,  203,  206,    0,    0,    0,
      133,   56,    0,    0,   22,   57,    0,    0,   58,    0,
        0,  151,  149,    0,    0,  209,  212,    0,  156,    0,
        0,    0,  231,    0,  170,  105,  109,  113,  111,  103,

      107,    0,  127,   52,    0,    0,    0,   47,  230,    0,
        0,  141,    0,    0,    0,    0,   45,  245,    0,  227,
        0,   44,  244,    0,  226,   59,    0,  150,  147,  235,
      238,  234,   62,    0,    0,    0,  146,    0,    0,  239,
       63,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    7,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    8,   18,   19,
       20,   21,    8,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   27,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   27,   27,   42,   27,   43,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       73,   74,   75,   76,   77,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[79] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[644] =
    {   0,
        0,  603,  646,  648,  601,  648,  624,  637,  648,  648,
       68,  648,  648,  628,  648,   69,  626,  624,   70,  648,
       72,   73,   75,  579,  585,   49,  584,   33,  648,  587,
      568,   41,  585,  584,  563,   39,  570,   53,  563,   58,
       58,   72,   60,  572,   46,  648,  648,  552,  648,  648,
       72,   77,   80,   89,   82,   85,  104,  578,   99,  577,
      109,  110,  114,  108,  119,   81,  125,  132,  125,   82,
      569,  567,  570,  648,  578,  648,  137,  648,  648,  648,
      615,  648,  610,  609,  608,  607,  606,  548,  648,  648,
      648,  648,  599,  648,  596,  181,  591,  648,  590,  648,

      648,  648,  648,  648,  138,  542,  545,  551,  543,  553,
      541,  544,  536,  549,  552,  539,  546,  648,  138,  530,
      533,  535,  648,  542,  648,  541,  536,  648,  529,  144,
      538,  648,  527,  536,  533,  526,  517,  532,  527,  516,
      648,  514,  528,  648,  136,  147,  528,  528,  151,  529,
      511,  508,  145,  518,  153,  150,  523,  509,  509,  165,
      503,  503,  520,  164,  505,  501,  503,  504,  512,  514,
      494,  165,  169,  493,  496,  498,  497,  496,  648,  501,
      483,  492,  501,  648,  502,  483,  648,  488,  496,  648,
      482,  490,  648,  483,  488,  481,  161,  492,  480,  174,

      475,  491,  181,  170,  486,  648,  481,  470,  470,  484,
      481,  648,  465,  648,  648,  648,  648,  648,  648,  648,
      648,  464,  648,  223,  648,  648,  467,  474,  480,  648,
      648,  462,  459,  648,  458,  468,  456,  648,  462,  454,
      464,  467,  470,  454,  467,  448,  460,  648,  462,  445,
      648,  444,  648,  443,  449,  460,  648,  440,  444,  449,
      456,  436,  167,  452,  438,  648,  445,  648,  190,  449,
      437,  648,  436,  239,  448,  648,  443,  435,  648,  431,
      427,  436,  435,  434,  648,  421,  422,  419,  648,  648,
      429,  648,  418,  648,  421,  201,  422,  421,  648,  429,

      242,  418,  411,  187,  425,  428,  412,  425,  648,  648,
      648,  648,  648,  648,  414,  209,  405,  417,  403,  648,
      195,  648,  648,  402,  407,  412,  648,  406,  410,  397,
      398,  396,  413,  196,  405,  648,  392,  396,  401,  201,
      252,  198,  408,  446,  440,  398,  404,  648,  389,  648,
      402,  390,  648,  400,  648,  386,  207,  648,  398,  394,
      648,  396,  375,  648,  648,  648,  394,  374,  392,  378,
      379,  648,  648,  382,  381,  380,  379,  385,  207,  218,
      384,  376,  375,  374,  195,  219,  648,  648,  648,  362,
      648,  361,  364,  648,  648,  648,  648,  373,  376,  364,

      355,  356,  372,  360,  648,  370,  648,  221,  223,  648,
      648,  350,  648,  355,  343,  217,  648,  366,  362,  364,
      355,  349,  648,  361,  352,  339,  339,  648,  354,  648,
      356,  648,  648,  648,  351,  335,  336,  348,  648,  351,
      337,  338,  333,  228,  340,  338,  338,  229,  231,  648,
      648,  648,  340,  648,  648,  377,  648,  648,  339,  648,
      327,  648,  332,  322,  320,  648,  337,  648,  334,  648,
      327,  648,  648,  320,  648,  648,  648,  648,  648,  223,
      331,  330,  318,  317,  648,  648,  648,  648,  648,  368,
      367,  648,  323,  323,  321,  648,  310,  305,  648,  311,

      310,  648,  648,  648,  359,  358,  648,  310,  648,  300,
      298,  648,  315,  648,  301,  648,  648,  313,  310,  297,
      648,  648,  291,  301,  290,  288,  648,  648,  292,  287,
      296,  648,  289,  296,  297,  648,  648,  339,  338,  648,
      648,  278,  284,  277,  295,  290,  648,  274,  278,  278,
      283,  282,  281,  280,  279,  278,  648,  648,  648,  264,
      648,  270,  648,  271,  648,  648,  648,  262,  280,  275,
      648,  648,  267,  258,  648,  648,  262,  271,  648,  261,
      265,  648,  648,  260,  252,  648,  648,  268,  648,  245,
      257,  265,  648,  253,  648,  648,  648,  648,  648,  648,

      648,  263,  648,  648,  240,  252,  260,  648,  648,  246,
      239,  648,  246,  256,  255,  235,  648,  648,  234,  648,
      233,  648,  648,  230,  648,  648,  232,  648,  648,  648,
      237,  648,  236,  230,  219,  163,  648,  122,  102,  648,
      648,  648,  106
    } ;

static yyconst flex_int16_t yy_def[644] =
    {   0,
      642,    1,  642,  642,  642,  642,  642,  643,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      643,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,    0,  642
    } ;

static yyconst flex_int16_t yy_nxt[727] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   29,   60,   61,
       62,   63,   64,   65,   29,   66,   67,   68,   69,   70,
       71,   72,   29,   73,   74,   75,   76,   77,   83,   84,
       90,   85,   86,   87,   95,   97,   96,   91,  102,   92,
       98,   99,  100,  101,  103,  104,  113,  107,  142,  114,

      115,  118,  119,  120,  108,  124,   81,  125,  127,  128,
      132,  109,  143,  133,  135,  110,   88,  111,  129,  130,
      137,  139,  145,  140,  134,  151,  136,  138,  153,  152,
      209,  146,  154,  147,  210,  155,  196,  148,  149,  150,
      159,  160,  156,  197,  165,  162,  157,  166,  158,  163,
      167,  161,  168,  164,  169,  172,  215,  176,  181,  177,
      173,  174,  185,  641,  188,  178,  182,  191,  189,  170,
      179,  180,  183,  190,  192,  193,  186,  198,  184,  199,
      204,  200,  187,  640,  194,  195,  207,  205,  208,  201,
      227,  241,  202,  203,  206,   95,  250,   96,  263,  265,

      251,  228,  264,  270,  403,  242,  266,  271,  276,  279,
      267,  277,  421,  281,  216,  280,  282,  283,  272,  287,
      293,  302,  304,  324,  288,  639,  303,  294,  328,  325,
      332,  335,  289,  374,  375,  329,  305,  345,  336,  224,
      379,  333,  385,  414,  334,  408,  426,  386,  437,  404,
      409,  488,  489,  443,  415,  448,  380,  381,  427,  452,
      449,  464,  438,  453,  444,  422,  445,  446,  447,  480,
      482,  510,  465,  481,  483,  490,  491,  503,  504,  505,
      506,  638,  511,  531,  532,  536,  537,  538,  539,  551,
      552,  637,  636,  635,  634,  387,  388,  633,  410,  411,

      632,  631,  630,  629,  628,  627,  626,  625,  450,  451,
      624,  623,  622,  621,  620,  619,  618,  617,  616,  615,
      614,  613,  612,  611,  610,  609,  608,  607,  606,  605,
      604,  603,  602,  601,  600,  599,  598,  597,  596,  595,
      594,  593,  592,  591,  590,  589,  588,  587,  586,  585,
      584,  583,  582,  581,  580,  579,  578,  577,  576,  575,
      574,  573,  572,  571,  570,  569,  568,  567,  566,  565,
      564,  563,  562,  561,  560,  559,  558,  557,  556,  555,
      554,  553,  550,  549,  548,  547,  546,  545,  544,  543,
      542,  541,  540,  535,  534,  533,  530,  529,  528,  527,

      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  509,  508,  507,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  487,
      486,  485,  484,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  442,  441,  440,
      439,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      425,  424,  423,  420,  419,  418,  417,  416,  413,  412,
      407,  406,  405,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  384,  383,  382,

      378,  377,  376,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  344,  343,  342,  341,  340,  339,  338,  337,  331,
      330,  327,  326,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  301,  300,  299,  298,  297,  296,  295,  292,  291,
      290,  286,  285,  284,  278,  275,  274,  273,  269,  268,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  249,  248,  247,  246,  245,  244,  243,  240,  239,

      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
       82,  214,  213,  212,  211,  175,  171,  144,  141,  131,
      126,  123,  122,  121,  117,  116,  112,  106,  105,   94,
       93,   89,   82,   80,   79,  642,   78,    3,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642
    } ;

static yyconst flex_int16_t yy_chk[727] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   11,   11,
       16,   11,   11,   11,   19,   21,   19,   16,   23,   16,
       21,   21,   22,   22,   23,   23,   28,   26,   45,   28,

       28,   32,   32,   32,   26,   36,  643,   36,   38,   38,
       40,   26,   45,   40,   41,   26,   11,   26,   38,   38,
       42,   43,   51,   43,   40,   52,   41,   42,   53,   52,
       70,   51,   53,   51,   70,   53,   66,   51,   51,   51,
       54,   54,   53,   66,   56,   55,   53,   56,   53,   55,
       56,   54,   57,   55,   57,   59,   77,   61,   62,   61,
       59,   59,   63,  639,   64,   61,   62,   65,   64,   57,
       61,   61,   62,   64,   65,   65,   63,   67,   62,   67,
       68,   67,   63,  638,   65,   65,   69,   68,   69,   67,
      105,  119,   67,   67,   68,   96,  130,   96,  145,  146,

      130,  105,  145,  149,  296,  119,  146,  149,  153,  155,
      146,  153,  316,  156,   77,  155,  156,  156,  149,  160,
      164,  172,  173,  197,  160,  636,  172,  164,  200,  197,
      203,  204,  160,  263,  263,  200,  173,  224,  204,  224,
      269,  203,  274,  304,  203,  301,  321,  274,  334,  296,
      301,  385,  385,  340,  304,  341,  269,  269,  321,  342,
      341,  357,  334,  342,  340,  316,  340,  340,  340,  379,
      380,  416,  357,  379,  380,  386,  386,  408,  408,  409,
      409,  635,  416,  444,  444,  448,  448,  449,  449,  480,
      480,  634,  633,  631,  627,  274,  274,  624,  301,  301,

      621,  619,  616,  615,  614,  613,  611,  610,  341,  341,
      607,  606,  605,  602,  594,  592,  591,  590,  588,  585,
      584,  581,  580,  578,  577,  574,  573,  570,  569,  568,
      564,  562,  560,  556,  555,  554,  553,  552,  551,  550,
      549,  548,  546,  545,  544,  543,  542,  539,  538,  535,
      534,  533,  531,  530,  529,  526,  525,  524,  523,  520,
      519,  518,  515,  513,  511,  510,  508,  506,  505,  501,
      500,  498,  497,  495,  494,  493,  491,  490,  484,  483,
      482,  481,  474,  471,  469,  467,  465,  464,  463,  461,
      459,  456,  453,  447,  446,  445,  443,  442,  441,  440,

      438,  437,  436,  435,  431,  429,  427,  426,  425,  424,
      422,  421,  420,  419,  418,  415,  414,  412,  406,  404,
      403,  402,  401,  400,  399,  398,  393,  392,  390,  384,
      383,  382,  381,  378,  377,  376,  375,  374,  371,  370,
      369,  368,  367,  363,  362,  360,  359,  356,  354,  352,
      351,  349,  347,  346,  345,  344,  343,  339,  338,  337,
      335,  333,  332,  331,  330,  329,  328,  326,  325,  324,
      319,  318,  317,  315,  308,  307,  306,  305,  303,  302,
      300,  298,  297,  295,  293,  291,  288,  287,  286,  284,
      283,  282,  281,  280,  278,  277,  275,  273,  271,  270,

      267,  265,  264,  262,  261,  260,  259,  258,  256,  255,
      254,  252,  250,  249,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  237,  236,  235,  233,  232,  229,  228,
      227,  222,  213,  211,  210,  209,  208,  207,  205,  202,
      201,  199,  198,  196,  195,  194,  192,  191,  189,  188,
      186,  185,  183,  182,  181,  180,  178,  177,  176,  175,
      174,  171,  170,  169,  168,  167,  166,  165,  163,  162,
      161,  159,  158,  157,  154,  152,  151,  150,  148,  147,
      143,  142,  140,  139,  138,  137,  136,  135,  134,  133,
      131,  129,  127,  126,  124,  122,  121,  120,  117,  116,

      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
       99,   97,   95,   93,   88,   87,   86,   85,   84,   83,
       81,   75,   73,   72,   71,   60,   58,   48,   44,   39,
       37,   35,   34,   33,   31,   30,   27,   25,   24,   18,
       17,   14,    8,    7,    5,    3,    2,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,

      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642,  642,  642,  642,  642,
      642,  642,  642,  642,  642,  642
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "math.l"
#line 2 "math.l"
#include "math.tab.h"
#line 835 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 5 "math.l"


#line 1028 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 643 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 648 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "math.l"
{ yylval = 0; return SOPT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "math.l"
{ yylval = 1; return SOPT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "math.l"
{ yylval = 2; return SOPT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "math.l"
{ yylval = 3; return SOPT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "math.l"
{ yylval = 4; return SOPT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "math.l"
{ yylval = 5; return SOPT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "math.l"
{ yylval = 6; return SOPT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 15 "math.l"
{ yylval = 7; return SOPT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "math.l"
{ yylval = 8; return SOPT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "math.l"
{ yylval = 9; return SOPT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 18 "math.l"
{ yylval = 10; return SOPT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 19 "math.l"
{ yylval = 11; return SOPT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "math.l"
{ yylval = 12; return SOPT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "math.l"
{ yylval = 13; return SOPT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 24 "math.l"
{ yylval = 14; return SOPT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "math.l"
{ yylval = 15; return SOPT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 26 "math.l"
{ yylval = 16; return SOPT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 29 "math.l"
{ yylval = 0; return SEQV; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 30 "math.l"
{ yylval = 1; return SEQV; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "math.l"
{ yylval = 2; return SEQV; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "math.l"
{ yylval = 3; return SEQV; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "math.l"
{ yylval = 4; return SEQV; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "math.l"
{ yylval = 5; return SEQV; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "math.l"
{ yylval = 6; return SEQV; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "math.l"
{ yylval = 7; return SEQV; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "math.l"
{ yylval = 8; return SEQV; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "math.l"
{ yylval = 9; return SEQV; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "math.l"
{ yylval = 10; return SEQV; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 40 "math.l"
{ yylval = 11; return SEQV; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 41 "math.l"
{ yylval = 12; return SEQV; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 42 "math.l"
{ yylval = 13; return SEQV; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "math.l"
{ yylval = 0; return SLGC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "math.l"
{ yylval = 1; return SLGC; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "math.l"
{ yylval = 2; return SLGC; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "math.l"
{ yylval = 3; return SLGC; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "math.l"
{ yylval = 4; return SLGC; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "math.l"
{ yylval = 5; return SLGC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "math.l"
{ yylval = 6; return SLGC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "math.l"
{ yylval = 7; return SLGC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "math.l"
{ yylval = 0; return SOTH; }
	YY_BREAK
case 41:
#line 57 "math.l"
case 42:
#line 58 "math.l"
case 43:
#line 59 "math.l"
case 44:
#line 60 "math.l"
case 45:
YY_RULE_SETUP
#line 60 "math.l"
{ yylval = 1; return SOTH; }
	YY_BREAK
case 46:
#line 63 "math.l"
case 47:
YY_RULE_SETUP
#line 63 "math.l"
{ yylval = 2; return SOTH; }
	YY_BREAK
case 48:
#line 65 "math.l"
case 49:
YY_RULE_SETUP
#line 65 "math.l"
{ yylval = 3; return SOTH; }
	YY_BREAK
case 50:
#line 69 "math.l"
case 51:
#line 70 "math.l"
case 52:
YY_RULE_SETUP
#line 70 "math.l"
{ yylval = 0; return SSET; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 "math.l"
{ yylval = 1; return SSET; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 73 "math.l"
{ yylval = 2; return SSET; }
	YY_BREAK
case 55:
#line 75 "math.l"
case 56:
YY_RULE_SETUP
#line 75 "math.l"
{ yylval = 3; return SSET; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 76 "math.l"
{ yylval = 4; return SSET; }
	YY_BREAK
case 58:
#line 78 "math.l"
case 59:
YY_RULE_SETUP
#line 78 "math.l"
{ yylval = 5; return SSET; }
	YY_BREAK
case 60:
#line 81 "math.l"
case 61:
YY_RULE_SETUP
#line 81 "math.l"
{ yylval = 6; return SSET; }
	YY_BREAK
case 62:
#line 83 "math.l"
case 63:
#line 84 "math.l"
case 64:
YY_RULE_SETUP
#line 84 "math.l"
{ yylval = 7; return SSET; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 85 "math.l"
{ yylval = 8; return SSET; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "math.l"
{ yylval = 0; return NSET; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "math.l"
{ yylval = 1; return NSET; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "math.l"
{ yylval = 2; return NSET; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "math.l"
{ yylval = 3; return NSET; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "math.l"
{ yylval = 4; return NSET; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "math.l"
{ yylval = 5; return NSET; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "math.l"
{ yylval = 6; return NSET; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "math.l"
{ yylval = 7; return NSET; }
	YY_BREAK
case 74:
#line 98 "math.l"
case 75:
YY_RULE_SETUP
#line 98 "math.l"
{ yylval = 8; return NSET; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "math.l"
{ yylval = 9; return NSET; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "math.l"
{ yylval = 10; return NSET; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 103 "math.l"
{ yylval = 0; return NTRI; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 104 "math.l"
{ yylval = 1; return NTRI; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 105 "math.l"
{ yylval = 2; return NTRI; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 106 "math.l"
{ yylval = 3; return NTRI; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 107 "math.l"
{ yylval = 4; return NTRI; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 108 "math.l"
{ yylval = 5; return NTRI; }
	YY_BREAK
case 84:
#line 110 "math.l"
case 85:
YY_RULE_SETUP
#line 110 "math.l"
{ yylval = 6; return NTRI; }
	YY_BREAK
case 86:
#line 112 "math.l"
case 87:
YY_RULE_SETUP
#line 112 "math.l"
{ yylval = 7; return NTRI; }
	YY_BREAK
case 88:
#line 114 "math.l"
case 89:
YY_RULE_SETUP
#line 114 "math.l"
{ yylval = 8; return NTRI; }
	YY_BREAK
case 90:
#line 116 "math.l"
case 91:
YY_RULE_SETUP
#line 116 "math.l"
{ yylval = 9; return NTRI; }
	YY_BREAK
case 92:
#line 118 "math.l"
case 93:
YY_RULE_SETUP
#line 118 "math.l"
{ yylval = 10; return NTRI; }
	YY_BREAK
case 94:
#line 120 "math.l"
case 95:
YY_RULE_SETUP
#line 120 "math.l"
{ yylval = 11; return NTRI; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 122 "math.l"
{ yylval = 0; return NHYB; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 123 "math.l"
{ yylval = 1; return NHYB; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 124 "math.l"
{ yylval = 2; return NHYB; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 125 "math.l"
{ yylval = 3; return NHYB; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 126 "math.l"
{ yylval = 4; return NHYB; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 127 "math.l"
{ yylval = 5; return NHYB; }
	YY_BREAK
case 102:
#line 129 "math.l"
case 103:
YY_RULE_SETUP
#line 129 "math.l"
{ yylval = 6; return NHYB; }
	YY_BREAK
case 104:
#line 131 "math.l"
case 105:
YY_RULE_SETUP
#line 131 "math.l"
{ yylval = 7; return NHYB; }
	YY_BREAK
case 106:
#line 133 "math.l"
case 107:
YY_RULE_SETUP
#line 133 "math.l"
{ yylval = 8; return NHYB; }
	YY_BREAK
case 108:
#line 135 "math.l"
case 109:
YY_RULE_SETUP
#line 135 "math.l"
{ yylval = 9; return NHYB; }
	YY_BREAK
case 110:
#line 137 "math.l"
case 111:
YY_RULE_SETUP
#line 137 "math.l"
{ yylval = 10; return NHYB; }
	YY_BREAK
case 112:
#line 139 "math.l"
case 113:
YY_RULE_SETUP
#line 139 "math.l"
{ yylval = 11; return NHYB; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 142 "math.l"
{ yylval = 0; return NEXP; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 143 "math.l"
{ yylval = 1; return NEXP; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 144 "math.l"
{ yylval = 2; return NEXP; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 147 "math.l"
{ yylval = 0; return NOTH; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 148 "math.l"
{ yylval = 1; return NOTH; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 149 "math.l"
{ yylval = 2; return NOTH; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 150 "math.l"
{ yylval = 3; return NOTH; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 151 "math.l"
{ yylval = 4; return NOTH; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 152 "math.l"
{ yylval = 5; return NOTH; }
	YY_BREAK
case 123:
#line 157 "math.l"
case 124:
#line 158 "math.l"
case 125:
#line 159 "math.l"
case 126:
#line 160 "math.l"
case 127:
#line 161 "math.l"
case 128:
#line 162 "math.l"
case 129:
#line 163 "math.l"
case 130:
#line 164 "math.l"
case 131:
#line 165 "math.l"
case 132:
#line 166 "math.l"
case 133:
#line 167 "math.l"
case 134:
#line 168 "math.l"
case 135:
#line 169 "math.l"
case 136:
#line 170 "math.l"
case 137:
#line 171 "math.l"
case 138:
#line 172 "math.l"
case 139:
#line 173 "math.l"
case 140:
#line 174 "math.l"
case 141:
#line 175 "math.l"
case 142:
#line 176 "math.l"
case 143:
#line 177 "math.l"
case 144:
#line 178 "math.l"
case 145:
YY_RULE_SETUP
#line 178 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 146:
#line 181 "math.l"
case 147:
#line 182 "math.l"
case 148:
#line 183 "math.l"
case 149:
#line 184 "math.l"
case 150:
#line 185 "math.l"
case 151:
YY_RULE_SETUP
#line 185 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 152:
#line 188 "math.l"
case 153:
#line 189 "math.l"
case 154:
#line 190 "math.l"
case 155:
#line 191 "math.l"
case 156:
#line 192 "math.l"
case 157:
#line 193 "math.l"
case 158:
#line 194 "math.l"
case 159:
#line 195 "math.l"
case 160:
#line 196 "math.l"
case 161:
#line 197 "math.l"
case 162:
#line 198 "math.l"
case 163:
#line 199 "math.l"
case 164:
#line 200 "math.l"
case 165:
#line 201 "math.l"
case 166:
#line 202 "math.l"
case 167:
#line 203 "math.l"
case 168:
#line 204 "math.l"
case 169:
#line 205 "math.l"
case 170:
#line 206 "math.l"
case 171:
#line 207 "math.l"
case 172:
#line 208 "math.l"
case 173:
#line 209 "math.l"
case 174:
YY_RULE_SETUP
#line 209 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 211 "math.l"
{ yylval = (int)yytext; return ENGL; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 212 "math.l"
{ yylval = (int)yytext; return PUNCT; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 213 "math.l"
{ yylval = (int)yytext; return ESCCH; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 215 "math.l"
{ yylval = (int)yytext; return NUMBER; }
	YY_BREAK
case 179:
/* rule 179 can match eol */
YY_RULE_SETUP
#line 217 "math.l"
{ yylval = (int)yytext; return TEXT; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 221 "math.l"
{ return OP; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 222 "math.l"
{ return CP; }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 224 "math.l"
{ return OS; }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 225 "math.l"
{ return CS; }
	YY_BREAK
case 184:
#line 228 "math.l"
case 185:
YY_RULE_SETUP
#line 228 "math.l"
{ return OB_M; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 229 "math.l"
{ return OB; }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 230 "math.l"
{ return CB; }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 231 "math.l"
{ return OL_M; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 232 "math.l"
{ return CL_M; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 236 "math.l"
{ return DIV; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 237 "math.l"
{ return POW; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 238 "math.l"
{ return CHS; }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 239 "math.l"
{ return NRT; }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 240 "math.l"
{ return SRT; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 242 "math.l"
{ return MOD; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 243 "math.l"
{ return FLR; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 244 "math.l"
{ return CIL; }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 245 "math.l"
{ return RND; }
	YY_BREAK
case 199:
#line 248 "math.l"
case 200:
YY_RULE_SETUP
#line 248 "math.l"
{ return SWC; }
	YY_BREAK
case 201:
#line 252 "math.l"
case 202:
#line 253 "math.l"
case 203:
YY_RULE_SETUP
#line 253 "math.l"
{ yylval = 0; return NOVR; }
	YY_BREAK
case 204:
#line 255 "math.l"
case 205:
#line 256 "math.l"
case 206:
YY_RULE_SETUP
#line 256 "math.l"
{ yylval = 1; return NOVR; }
	YY_BREAK
case 207:
#line 258 "math.l"
case 208:
#line 259 "math.l"
case 209:
YY_RULE_SETUP
#line 259 "math.l"
{ yylval = 2; return NOVR; }
	YY_BREAK
case 210:
#line 261 "math.l"
case 211:
#line 262 "math.l"
case 212:
YY_RULE_SETUP
#line 262 "math.l"
{ yylval = 3; return NOVR; }
	YY_BREAK
case 213:
#line 264 "math.l"
case 214:
#line 265 "math.l"
case 215:
YY_RULE_SETUP
#line 265 "math.l"
{ yylval = 4; return NOVR; }
	YY_BREAK
case 216:
#line 267 "math.l"
case 217:
#line 268 "math.l"
case 218:
YY_RULE_SETUP
#line 268 "math.l"
{ yylval = 5; return NOVR; }
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 271 "math.l"
{ yylval = 0; return OOVR; }
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 272 "math.l"
{ yylval = 1; return OOVR; }
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 273 "math.l"
{ yylval = 2; return OOVR; }
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 274 "math.l"
{ yylval = 3; return OOVR; }
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 275 "math.l"
{ yylval = 4; return OOVR; }
	YY_BREAK
case 224:
#line 279 "math.l"
case 225:
#line 280 "math.l"
case 226:
#line 281 "math.l"
case 227:
YY_RULE_SETUP
#line 281 "math.l"
{ yylval = 0; return OSUM; }
	YY_BREAK
case 228:
#line 284 "math.l"
case 229:
#line 285 "math.l"
case 230:
#line 286 "math.l"
case 231:
YY_RULE_SETUP
#line 286 "math.l"
{ yylval = 1; return OSUM; }
	YY_BREAK
case 232:
#line 289 "math.l"
case 233:
#line 290 "math.l"
case 234:
#line 291 "math.l"
case 235:
YY_RULE_SETUP
#line 291 "math.l"
{ yylval = 2; return OSUM; }
	YY_BREAK
case 236:
#line 294 "math.l"
case 237:
YY_RULE_SETUP
#line 294 "math.l"
{ yylval = 3; return OSUM; }
	YY_BREAK
case 238:
#line 296 "math.l"
case 239:
#line 297 "math.l"
case 240:
YY_RULE_SETUP
#line 297 "math.l"
{ yylval = 4; return OSUM; }
	YY_BREAK
case 241:
YY_RULE_SETUP
#line 299 "math.l"
{ yylval = 5; return OSUM; }
	YY_BREAK
case 242:
#line 302 "math.l"
case 243:
#line 303 "math.l"
case 244:
#line 304 "math.l"
case 245:
YY_RULE_SETUP
#line 304 "math.l"
{ yylval = 6; return OSUM; }
	YY_BREAK
case 246:
YY_RULE_SETUP
#line 306 "math.l"
{ yylval = 7; return OSUM; }
	YY_BREAK
case 247:
YY_RULE_SETUP
#line 307 "math.l"
{ yylval = 8; return OSUM; }
	YY_BREAK
case 248:
YY_RULE_SETUP
#line 308 "math.l"
{ yylval = 9; return OSUM; }
	YY_BREAK
case 249:
YY_RULE_SETUP
#line 311 "math.l"
{ return FR; }
	YY_BREAK
case 250:
YY_RULE_SETUP
#line 312 "math.l"
{ return TO; }
	YY_BREAK
case 251:
#line 314 "math.l"
case 252:
YY_RULE_SETUP
#line 314 "math.l"
{ return WH; }
	YY_BREAK
case 253:
YY_RULE_SETUP
#line 317 "math.l"
{ return SPC; }
	YY_BREAK
case 254:
YY_RULE_SETUP
#line 318 "math.l"
{ return SEP; }
	YY_BREAK
case 255:
YY_RULE_SETUP
#line 319 "math.l"
{ return SNL; }
	YY_BREAK
case 256:
/* rule 256 can match eol */
YY_RULE_SETUP
#line 320 "math.l"
{ return EOL; }
	YY_BREAK
case 257:
YY_RULE_SETUP
#line 321 "math.l"
{ }
	YY_BREAK
case 258:
YY_RULE_SETUP
#line 322 "math.l"
{ printf("Unknown: %c\n", *yytext); }
	YY_BREAK
case 259:
YY_RULE_SETUP
#line 324 "math.l"
ECHO;
	YY_BREAK
#line 2094 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 643 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 643 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 642);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 324 "math.l"


