
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 269
#define YY_END_OF_BUFFER 270
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[667] =
    {   0,
        0,    0,  270,  268,  267,  266,  268,  179,  268,  265,
      179,  180,  183,  184,    3,    1,  263,    2,    4,  196,
      181,  264,   26,   20,   27,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  190,   67,  191,
      197,  262,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  185,   19,  186,   15,  187,
      188,  266,   25,    0,  182,    0,    0,    0,    0,    0,
        0,   13,   14,   32,   35,    0,    6,    0,  181,   34,

       28,   30,   21,   37,   33,   31,   29,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       80,    0,    0,    0,    0,  166,    0,  167,    0,    0,
        0,  169,    0,    0,    0,   79,    0,    0,    0,    0,
        0,    0,    0,    0,  168,    0,    0,  193,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   56,    0,    0,
        0,    0,    0,  119,    0,    0,    0,    0,  137,    0,
        0,  138,    0,    0,   40,    0,    0,  140,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      259,    0,    0,    0,    0,    0,  139,    0,  192,   18,
       22,   23,    9,    7,    8,   10,   12,    0,   42,  181,
       36,   38,    0,    0,    0,  246,  175,    0,    0,  243,
        0,    0,    0,  161,    0,    0,   44,  249,    0,    0,
        0,    0,    0,    0,  174,    0,    0,  176,    0,  170,
        0,    0,  231,  172,    0,    0,    0,    0,    0,  195,
        0,    0,    0,   52,    0,   39,    0,    0,    0,    5,
        0,  229,    0,   66,    0,    0,  146,    0,    0,   82,
       84,   86,   63,    0,    0,    0,  125,  225,    0,    0,

      132,    0,  117,    0,    0,    0,    0,  123,    0,  227,
        0,    0,   43,  248,    0,    0,    0,  124,  247,  118,
      121,  122,  201,    0,   41,    0,    0,    0,  145,    0,
      147,  141,    0,    0,   85,  120,    0,   81,    0,    0,
        0,  230,    0,   83,  143,    0,    0,    0,    0,  228,
        0,    0,  194,    0,    0,    0,    0,  156,    0,   75,
        0,    0,   69,    0,   76,    0,    0,  163,    0,    0,
       70,  253,    0,  235,   72,   73,   74,    0,    0,    0,
        0,    0,  160,   71,   89,   93,   97,    0,    0,    0,
        0,    0,   95,   87,   91,    0,    0,  219,  222,  127,

      205,  203,    0,    0,  100,  102,  104,  226,    0,    0,
      189,    0,    0,    0,    0,    0,    0,  258,    0,   50,
        0,    0,  207,  210,    0,  256,    0,    0,    0,  134,
        0,    0,    0,    0,    0,  252,    0,   48,  234,    0,
      199,    0,  103,    0,   99,  200,   17,    0,    0,    0,
        0,  101,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  213,  216,  260,    0,  131,   11,    0,   78,
      155,    0,  158,    0,  157,    0,    0,    0,  164,    0,
        0,  177,    0,  171,    0,  162,  242,    0,  107,  111,
      115,   77,  126,    0,    0,    0,    0,    0,  113,  105,

      109,  220,  223,    0,    0,  206,    0,    0,    0,  129,
       68,    0,    0,  202,    0,    0,  128,  208,  211,    0,
        0,  257,    0,   45,    0,    0,  135,    0,   51,    0,
       57,    0,  148,    0,    0,    0,  204,  142,    0,    0,
        0,    0,  133,   62,    0,    0,    0,  151,    0,    0,
        0,  214,  217,    0,    0,  261,  181,  239,    0,    0,
        0,    0,  165,    0,    0,    0,    0,   90,   94,   98,
       96,   88,   92,  221,  224,  198,  238,   16,    0,   55,
        0,   53,  209,  212,    0,    0,    0,  136,   58,    0,
        0,    0,   24,   59,    0,    0,   60,    0,    0,  154,

      152,    0,    0,  215,  218,    0,  159,    0,    0,    0,
        0,  237,    0,  173,  108,  112,  116,  114,  106,  110,
        0,  130,   54,    0,    0,    0,    0,   49,  236,    0,
        0,  144,    0,    0,    0,    0,   47,  251,    0,    0,
      233,    0,   46,  250,    0,    0,  232,   61,    0,  153,
      150,  241,  244,  255,  240,   64,  254,    0,    0,    0,
      149,    0,    0,  245,   65,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   10,    9,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    9,   20,   21,
       22,   23,    9,    9,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   29,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   29,   29,   44,   29,   45,
       46,   47,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[668] =
    {   0,
        0,  625,  670,  672,  623,  672,  665,  645,  659,  672,
      672,  672,   68,  672,  672,  649,  672,   69,  647,  645,
       70,  672,   72,   73,   75,  600,  606,   49,  605,   33,
      672,  608,  589,   41,  606,  605,  584,   39,   50,   53,
      585,   68,   56,   66,   64,  594,   70,  672,  672,  574,
      672,  672,   76,   80,   92,   87,   85,  100,   81,  600,
      105,  599,  107,  116,  123,  114,  127,  118,  134,  141,
       90,  129,  591,  589,  592,  672,   55,  672,  131,  672,
      672,  672,  672,  639,  672,  633,  632,  631,  630,  629,
      571,  672,  672,  672,  672,  622,  672,  619,  181,  614,

      672,  613,  672,  672,  672,  672,  672,  124,  565,  568,
      574,  566,  576,  564,  567,  559,  572,  575,  562,  569,
      672,  146,  553,  556,  558,  672,  565,  672,  555,  563,
      558,  672,  551,  148,  560,  672,  549,  558,  555,  548,
      539,  554,  549,  538,  672,  536,  550,  526,  143,  155,
      549,  549,  154,  550,  532,  529,  149,  539,  155,  153,
      544,  530,  530,  168,  524,  527,  523,  540,  167,  525,
      521,  523,  524,  532,  534,  514,  168,  172,  513,  516,
      518,  517,  516,  672,  521,  503,  512,  521,  672,  522,
      503,  672,  508,  516,  672,  502,  510,  672,  503,  508,

      501,  164,  512,  500,  177,  495,  511,  184,  173,  506,
      672,  501,  490,  490,  504,  501,  672,  485,  672,  508,
      672,  672,  672,  672,  672,  672,  672,  483,  672,  226,
      672,  672,  486,  493,  499,  672,  672,  481,  478,  672,
      477,  487,  475,  672,  481,  473,  483,  486,  489,  473,
      486,  467,  466,  478,  672,  480,  463,  672,  462,  672,
      461,  467,  478,  672,  458,  462,  467,  474,  454,  672,
      170,  470,  456,  672,  463,  672,  193,  467,  455,  672,
      454,  243,  466,  672,  461,  453,  672,  449,  445,  454,
      453,  452,  672,  439,  440,  437,  460,  672,  435,  445,

      672,  434,  672,  437,  226,  438,  437,  672,  445,  246,
      434,  427,  190,  441,  444,  428,  441,  672,  672,  672,
      672,  672,  672,  430,  248,  421,  433,  419,  672,  198,
      672,  672,  418,  423,  428,  672,  422,  426,  413,  414,
      412,  429,  200,  421,  672,  408,  412,  417,  204,  256,
      207,  424,  672,  462,  456,  414,  420,  672,  405,  672,
      418,  406,  672,  416,  672,  402,  208,  672,  414,  410,
      672,  408,  411,  390,  672,  672,  672,  409,  389,  407,
      393,  394,  672,  672,  397,  396,  395,  394,  400,  213,
      224,  399,  391,  390,  389,  221,  225,  672,  672,  672,

      377,  672,  376,  379,  672,  672,  672,  672,  388,  391,
      672,  366,  378,  369,  370,  386,  374,  672,  384,  672,
      227,  229,  672,  672,  364,  672,  369,  357,  233,  672,
      380,  376,  378,  369,  363,  371,  374,  365,  352,  352,
      672,  367,  672,  369,  672,  672,  672,  364,  348,  349,
      361,  672,  364,  350,  351,  346,  233,  353,  351,  351,
      234,  236,  672,  672,  672,  353,  672,  672,  390,  672,
      672,  352,  672,  340,  672,  345,  335,  333,  672,  350,
      343,  672,  346,  672,  339,  672,  672,  332,  672,  672,
      672,  672,  672,  228,  343,  342,  330,  329,  672,  672,

      672,  672,  672,  380,  379,  672,  335,  335,  333,  672,
      672,  322,  317,  672,  323,  322,  672,  672,  672,  371,
      370,  672,  322,  672,  312,  310,  672,  327,  672,  313,
      672,  319,  672,  324,  321,  308,  672,  672,  302,  312,
      301,  299,  672,  672,  303,  298,  307,  672,  300,  307,
      308,  672,  672,  350,  349,  672,  672,  289,  295,  288,
      306,  301,  672,  287,  284,  288,  288,  293,  292,  291,
      290,  289,  288,  672,  672,  672,  274,  672,  280,  672,
      281,  672,  672,  672,  272,  290,  285,  672,  672,  271,
      276,  267,  672,  672,  271,  280,  672,  270,  274,  672,

      672,  269,  261,  672,  672,  277,  672,  254,  266,  274,
      275,  672,  261,  672,  672,  672,  672,  672,  672,  672,
      271,  672,  672,  248,  260,  268,  269,  672,  672,  255,
      248,  672,  255,  263,  262,  242,  672,  672,  241,  248,
      672,  239,  672,  672,  238,  242,  672,  672,  235,  672,
      672,  672,  240,  672,  672,  209,  672,  202,  193,  191,
      672,  133,   72,  672,  672,  672,  115
    } ;

static yyconst flex_int16_t yy_def[668] =
    {   0,
      666,    1,  666,  666,  666,  666,  666,  666,  667,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  667,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,    0,  666
    } ;

static yyconst flex_int16_t yy_nxt[753] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   31,
       62,   63,   64,   65,   66,   67,   31,   68,   69,   70,
       71,   72,   73,   74,   31,   75,   76,   77,   78,   79,
       86,   87,   93,   88,   89,   90,   98,  100,   99,   94,
      105,   95,  101,  102,  103,  104,  106,  107,  116,  110,

      219,  117,  118,  121,  122,  123,  111,  127,  129,  128,
      131,  132,  130,  112,  139,   84,  141,  113,   91,  114,
      133,  134,  136,  142,  146,  137,  140,  143,  149,  144,
      155,  173,  220,  174,  156,  665,  138,  150,  147,  151,
      163,  164,  157,  152,  153,  154,  158,  166,  175,  159,
      167,  165,  221,  212,  168,  213,  160,  181,  169,  182,
      161,  170,  162,  177,  171,  183,  186,  172,  178,  179,
      184,  185,  193,  190,  187,  201,  194,  196,  233,  214,
      188,  195,  202,  215,  197,  198,  189,  191,  203,  234,
      204,  209,  205,  192,  199,  200,  664,   98,  210,   99,

      206,  247,  257,  207,  208,  211,  258,  271,  278,  273,
      222,  272,  279,  287,  284,  248,  274,  285,  289,  288,
      275,  290,  291,  280,  295,  302,  311,  313,  333,  296,
      416,  312,  303,  337,  334,  341,  344,  297,  385,  386,
      338,  314,  355,  345,  230,  390,  342,  396,  427,  343,
      421,  439,  434,  397,  450,  663,  422,  662,  456,  428,
      461,  391,  392,  440,  477,  661,  462,  660,  451,  457,
      465,  458,  459,  460,  466,  478,  417,  494,  496,  502,
      503,  495,  497,  504,  505,  518,  519,  520,  521,  525,
      547,  548,  552,  553,  554,  555,  568,  569,  659,  658,

      526,  398,  399,  657,  423,  424,  435,  656,  655,  654,
      653,  652,  651,  650,  463,  464,  649,  648,  647,  646,
      645,  644,  643,  642,  641,  640,  639,  638,  637,  636,
      635,  634,  633,  632,  631,  630,  629,  628,  627,  626,
      625,  624,  623,  622,  621,  620,  619,  618,  617,  616,
      615,  614,  613,  612,  611,  610,  609,  608,  607,  606,
      605,  604,  603,  602,  601,  600,  599,  598,  597,  596,
      595,  594,  593,  592,  591,  590,  589,  588,  587,  586,
      585,  584,  583,  582,  581,  580,  579,  578,  577,  576,
      575,  574,  573,  572,  571,  570,  567,  566,  565,  564,

      563,  562,  561,  560,  559,  558,  557,  556,  551,  550,
      549,  546,  545,  544,  543,  542,  541,  540,  539,  538,
      537,  536,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  524,  523,  522,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  501,  500,  499,  498,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  476,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  455,  454,  453,  452,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  438,  437,
      436,  433,  432,  431,  430,  429,  426,  425,  420,  419,

      418,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  395,  394,  393,
      389,  388,  387,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  340,  339,  336,  335,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  310,  309,  308,  307,  306,  305,  304,
      301,  300,  299,  298,  294,  293,  292,  286,  283,  282,

      281,  277,  276,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  256,  255,  254,  253,  252,
      251,  250,  249,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,   85,  218,  217,  216,  180,
      176,  148,  145,  135,  126,  125,  124,  120,  119,  115,
      109,  108,   97,   96,   92,   85,   83,   82,   81,  666,
       80,    3,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666
    } ;

static yyconst flex_int16_t yy_chk[753] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       13,   13,   18,   13,   13,   13,   21,   23,   21,   18,
       25,   18,   23,   23,   24,   24,   25,   25,   30,   28,

       77,   30,   30,   34,   34,   34,   28,   38,   39,   38,
       40,   40,   39,   28,   43,  667,   44,   28,   13,   28,
       40,   40,   42,   44,   47,   42,   43,   45,   53,   45,
       54,   59,   77,   59,   54,  663,   42,   53,   47,   53,
       56,   56,   55,   53,   53,   53,   55,   57,   59,   55,
       57,   56,   79,   71,   57,   71,   55,   63,   57,   63,
       55,   58,   55,   61,   58,   63,   64,   58,   61,   61,
       63,   63,   66,   65,   64,   68,   66,   67,  108,   72,
       64,   66,   68,   72,   67,   67,   64,   65,   69,  108,
       69,   70,   69,   65,   67,   67,  662,   99,   70,   99,

       69,  122,  134,   69,   69,   70,  134,  149,  153,  150,
       79,  149,  153,  159,  157,  122,  150,  157,  160,  159,
      150,  160,  160,  153,  164,  169,  177,  178,  202,  164,
      305,  177,  169,  205,  202,  208,  209,  164,  271,  271,
      205,  178,  230,  209,  230,  277,  208,  282,  313,  208,
      310,  330,  325,  282,  343,  660,  310,  659,  349,  313,
      350,  277,  277,  330,  367,  658,  350,  656,  343,  349,
      351,  349,  349,  349,  351,  367,  305,  390,  391,  396,
      396,  390,  391,  397,  397,  421,  421,  422,  422,  429,
      457,  457,  461,  461,  462,  462,  494,  494,  653,  649,

      429,  282,  282,  646,  310,  310,  325,  645,  642,  640,
      639,  636,  635,  634,  350,  350,  633,  631,  630,  627,
      626,  625,  624,  621,  613,  611,  610,  609,  608,  606,
      603,  602,  599,  598,  596,  595,  592,  591,  590,  587,
      586,  585,  581,  579,  577,  573,  572,  571,  570,  569,
      568,  567,  566,  565,  564,  562,  561,  560,  559,  558,
      555,  554,  551,  550,  549,  547,  546,  545,  542,  541,
      540,  539,  536,  535,  534,  532,  530,  528,  526,  525,
      523,  521,  520,  516,  515,  513,  512,  509,  508,  507,
      505,  504,  498,  497,  496,  495,  488,  485,  483,  481,

      480,  478,  477,  476,  474,  472,  469,  466,  460,  459,
      458,  456,  455,  454,  453,  451,  450,  449,  448,  444,
      442,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  428,  427,  425,  419,  417,  416,  415,  414,  413,
      412,  410,  409,  404,  403,  401,  395,  394,  393,  392,
      389,  388,  387,  386,  385,  382,  381,  380,  379,  378,
      374,  373,  372,  370,  369,  366,  364,  362,  361,  359,
      357,  356,  355,  354,  352,  348,  347,  346,  344,  342,
      341,  340,  339,  338,  337,  335,  334,  333,  328,  327,
      326,  324,  317,  316,  315,  314,  312,  311,  309,  307,

      306,  304,  302,  300,  299,  297,  296,  295,  294,  292,
      291,  290,  289,  288,  286,  285,  283,  281,  279,  278,
      275,  273,  272,  269,  268,  267,  266,  265,  263,  262,
      261,  259,  257,  256,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  243,  242,  241,  239,  238,  235,
      234,  233,  228,  220,  218,  216,  215,  214,  213,  212,
      210,  207,  206,  204,  203,  201,  200,  199,  197,  196,
      194,  193,  191,  190,  188,  187,  186,  185,  183,  182,
      181,  180,  179,  176,  175,  174,  173,  172,  171,  170,
      168,  167,  166,  165,  163,  162,  161,  158,  156,  155,

      154,  152,  151,  148,  147,  146,  144,  143,  142,  141,
      140,  139,  138,  137,  135,  133,  131,  130,  129,  127,
      125,  124,  123,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  102,  100,   98,   96,   91,
       90,   89,   88,   87,   86,   84,   75,   74,   73,   62,
       60,   50,   46,   41,   37,   36,   35,   33,   32,   29,
       27,   26,   20,   19,   16,    9,    8,    7,    5,    3,
        2,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "math.l"
#line 2 "math.l"
#include "math.tab.h"
#line 847 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 5 "math.l"


#line 1040 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 667 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 672 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "math.l"
{ yylval = 0; return SOPT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "math.l"
{ yylval = 1; return SOPT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "math.l"
{ yylval = 2; return SOPT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "math.l"
{ yylval = 3; return SOPT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "math.l"
{ yylval = 4; return SOPT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "math.l"
{ yylval = 5; return SOPT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "math.l"
{ yylval = 6; return SOPT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 15 "math.l"
{ yylval = 7; return SOPT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "math.l"
{ yylval = 8; return SOPT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "math.l"
{ yylval = 9; return SOPT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 18 "math.l"
{ yylval = 10; return SOPT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 19 "math.l"
{ yylval = 11; return SOPT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "math.l"
{ yylval = 12; return SOPT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "math.l"
{ yylval = 13; return SOPT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 24 "math.l"
{ yylval = 14; return SOPT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "math.l"
{ yylval = 15; return SOPT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 26 "math.l"
{ yylval = 16; return SOPT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "math.l"
{ yylval = 17; return SOPT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "math.l"
{ yylval = 18; return SOPT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "math.l"
{ yylval = 0; return SEQV; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "math.l"
{ yylval = 1; return SEQV; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "math.l"
{ yylval = 2; return SEQV; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "math.l"
{ yylval = 3; return SEQV; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "math.l"
{ yylval = 4; return SEQV; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "math.l"
{ yylval = 5; return SEQV; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "math.l"
{ yylval = 6; return SEQV; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "math.l"
{ yylval = 7; return SEQV; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "math.l"
{ yylval = 8; return SEQV; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 40 "math.l"
{ yylval = 9; return SEQV; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 41 "math.l"
{ yylval = 10; return SEQV; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 42 "math.l"
{ yylval = 11; return SEQV; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 43 "math.l"
{ yylval = 12; return SEQV; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 44 "math.l"
{ yylval = 13; return SEQV; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "math.l"
{ yylval = 0; return SLGC; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "math.l"
{ yylval = 1; return SLGC; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "math.l"
{ yylval = 2; return SLGC; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "math.l"
{ yylval = 3; return SLGC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "math.l"
{ yylval = 4; return SLGC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "math.l"
{ yylval = 5; return SLGC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "math.l"
{ yylval = 6; return SLGC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "math.l"
{ yylval = 7; return SLGC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "math.l"
{ yylval = 0; return SOTH; }
	YY_BREAK
case 43:
#line 59 "math.l"
case 44:
#line 60 "math.l"
case 45:
#line 61 "math.l"
case 46:
#line 62 "math.l"
case 47:
YY_RULE_SETUP
#line 62 "math.l"
{ yylval = 1; return SOTH; }
	YY_BREAK
case 48:
#line 65 "math.l"
case 49:
YY_RULE_SETUP
#line 65 "math.l"
{ yylval = 2; return SOTH; }
	YY_BREAK
case 50:
#line 67 "math.l"
case 51:
YY_RULE_SETUP
#line 67 "math.l"
{ yylval = 3; return SOTH; }
	YY_BREAK
case 52:
#line 71 "math.l"
case 53:
#line 72 "math.l"
case 54:
YY_RULE_SETUP
#line 72 "math.l"
{ yylval = 0; return SSET; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 "math.l"
{ yylval = 1; return SSET; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 75 "math.l"
{ yylval = 2; return SSET; }
	YY_BREAK
case 57:
#line 77 "math.l"
case 58:
YY_RULE_SETUP
#line 77 "math.l"
{ yylval = 3; return SSET; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 78 "math.l"
{ yylval = 4; return SSET; }
	YY_BREAK
case 60:
#line 80 "math.l"
case 61:
YY_RULE_SETUP
#line 80 "math.l"
{ yylval = 5; return SSET; }
	YY_BREAK
case 62:
#line 83 "math.l"
case 63:
YY_RULE_SETUP
#line 83 "math.l"
{ yylval = 6; return SSET; }
	YY_BREAK
case 64:
#line 85 "math.l"
case 65:
#line 86 "math.l"
case 66:
YY_RULE_SETUP
#line 86 "math.l"
{ yylval = 7; return SSET; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 87 "math.l"
{ yylval = 8; return SSET; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 90 "math.l"
{ yylval = 0; return NSET; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "math.l"
{ yylval = 1; return NSET; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 92 "math.l"
{ yylval = 2; return NSET; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 93 "math.l"
{ yylval = 3; return NSET; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "math.l"
{ yylval = 4; return NSET; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "math.l"
{ yylval = 5; return NSET; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 96 "math.l"
{ yylval = 6; return NSET; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 97 "math.l"
{ yylval = 7; return NSET; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 98 "math.l"
{ yylval = 8; return NSET; }
	YY_BREAK
case 77:
#line 100 "math.l"
case 78:
YY_RULE_SETUP
#line 100 "math.l"
{ yylval = 9; return NSET; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 101 "math.l"
{ yylval = 10; return NSET; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 102 "math.l"
{ yylval = 11; return NSET; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 105 "math.l"
{ yylval = 0; return NTRI; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 106 "math.l"
{ yylval = 1; return NTRI; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 107 "math.l"
{ yylval = 2; return NTRI; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 108 "math.l"
{ yylval = 3; return NTRI; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 109 "math.l"
{ yylval = 4; return NTRI; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 110 "math.l"
{ yylval = 5; return NTRI; }
	YY_BREAK
case 87:
#line 112 "math.l"
case 88:
YY_RULE_SETUP
#line 112 "math.l"
{ yylval = 6; return NTRI; }
	YY_BREAK
case 89:
#line 114 "math.l"
case 90:
YY_RULE_SETUP
#line 114 "math.l"
{ yylval = 7; return NTRI; }
	YY_BREAK
case 91:
#line 116 "math.l"
case 92:
YY_RULE_SETUP
#line 116 "math.l"
{ yylval = 8; return NTRI; }
	YY_BREAK
case 93:
#line 118 "math.l"
case 94:
YY_RULE_SETUP
#line 118 "math.l"
{ yylval = 9; return NTRI; }
	YY_BREAK
case 95:
#line 120 "math.l"
case 96:
YY_RULE_SETUP
#line 120 "math.l"
{ yylval = 10; return NTRI; }
	YY_BREAK
case 97:
#line 122 "math.l"
case 98:
YY_RULE_SETUP
#line 122 "math.l"
{ yylval = 11; return NTRI; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 124 "math.l"
{ yylval = 0; return NHYB; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 125 "math.l"
{ yylval = 1; return NHYB; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 126 "math.l"
{ yylval = 2; return NHYB; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 127 "math.l"
{ yylval = 3; return NHYB; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 128 "math.l"
{ yylval = 4; return NHYB; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 129 "math.l"
{ yylval = 5; return NHYB; }
	YY_BREAK
case 105:
#line 131 "math.l"
case 106:
YY_RULE_SETUP
#line 131 "math.l"
{ yylval = 6; return NHYB; }
	YY_BREAK
case 107:
#line 133 "math.l"
case 108:
YY_RULE_SETUP
#line 133 "math.l"
{ yylval = 7; return NHYB; }
	YY_BREAK
case 109:
#line 135 "math.l"
case 110:
YY_RULE_SETUP
#line 135 "math.l"
{ yylval = 8; return NHYB; }
	YY_BREAK
case 111:
#line 137 "math.l"
case 112:
YY_RULE_SETUP
#line 137 "math.l"
{ yylval = 9; return NHYB; }
	YY_BREAK
case 113:
#line 139 "math.l"
case 114:
YY_RULE_SETUP
#line 139 "math.l"
{ yylval = 10; return NHYB; }
	YY_BREAK
case 115:
#line 141 "math.l"
case 116:
YY_RULE_SETUP
#line 141 "math.l"
{ yylval = 11; return NHYB; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 144 "math.l"
{ yylval = 0; return NEXP; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 145 "math.l"
{ yylval = 1; return NEXP; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 146 "math.l"
{ yylval = 2; return NEXP; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 149 "math.l"
{ yylval = 0; return NOTH; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 150 "math.l"
{ yylval = 1; return NOTH; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 151 "math.l"
{ yylval = 2; return NOTH; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 152 "math.l"
{ yylval = 3; return NOTH; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 153 "math.l"
{ yylval = 4; return NOTH; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 154 "math.l"
{ yylval = 5; return NOTH; }
	YY_BREAK
case 126:
#line 159 "math.l"
case 127:
#line 160 "math.l"
case 128:
#line 161 "math.l"
case 129:
#line 162 "math.l"
case 130:
#line 163 "math.l"
case 131:
#line 164 "math.l"
case 132:
#line 165 "math.l"
case 133:
#line 166 "math.l"
case 134:
#line 167 "math.l"
case 135:
#line 168 "math.l"
case 136:
#line 169 "math.l"
case 137:
#line 170 "math.l"
case 138:
#line 171 "math.l"
case 139:
#line 172 "math.l"
case 140:
#line 173 "math.l"
case 141:
#line 174 "math.l"
case 142:
#line 175 "math.l"
case 143:
#line 176 "math.l"
case 144:
#line 177 "math.l"
case 145:
#line 178 "math.l"
case 146:
#line 179 "math.l"
case 147:
#line 180 "math.l"
case 148:
YY_RULE_SETUP
#line 180 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 149:
#line 183 "math.l"
case 150:
#line 184 "math.l"
case 151:
#line 185 "math.l"
case 152:
#line 186 "math.l"
case 153:
#line 187 "math.l"
case 154:
YY_RULE_SETUP
#line 187 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 155:
#line 190 "math.l"
case 156:
#line 191 "math.l"
case 157:
#line 192 "math.l"
case 158:
#line 193 "math.l"
case 159:
#line 194 "math.l"
case 160:
#line 195 "math.l"
case 161:
#line 196 "math.l"
case 162:
#line 197 "math.l"
case 163:
#line 198 "math.l"
case 164:
#line 199 "math.l"
case 165:
#line 200 "math.l"
case 166:
#line 201 "math.l"
case 167:
#line 202 "math.l"
case 168:
#line 203 "math.l"
case 169:
#line 204 "math.l"
case 170:
#line 205 "math.l"
case 171:
#line 206 "math.l"
case 172:
#line 207 "math.l"
case 173:
#line 208 "math.l"
case 174:
#line 209 "math.l"
case 175:
#line 210 "math.l"
case 176:
#line 211 "math.l"
case 177:
YY_RULE_SETUP
#line 211 "math.l"
{ yylval = (int)yytext; return GREEK; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 213 "math.l"
{ yylval = (int)yytext; return ENGL; }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 214 "math.l"
{ yylval = (int)yytext; return PUNCT; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 215 "math.l"
{ yylval = (int)yytext; return ESCCH; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 217 "math.l"
{ yylval = (int)yytext; return NUMBER; }
	YY_BREAK
case 182:
/* rule 182 can match eol */
YY_RULE_SETUP
#line 219 "math.l"
{ yylval = (int)yytext; return TEXT; }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 223 "math.l"
{ return OP; }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 224 "math.l"
{ return CP; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 226 "math.l"
{ return OS; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 227 "math.l"
{ return CS; }
	YY_BREAK
case 187:
#line 230 "math.l"
case 188:
YY_RULE_SETUP
#line 230 "math.l"
{ return OB_M; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 231 "math.l"
{ return OB_D; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 232 "math.l"
{ return OB; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 233 "math.l"
{ return CB; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 234 "math.l"
{ return OL_M; }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 235 "math.l"
{ return CL_M; }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 236 "math.l"
{ return OL_D; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 237 "math.l"
{ return CL_D; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 241 "math.l"
{ return DIV; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 242 "math.l"
{ return POW; }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 243 "math.l"
{ return CHS; }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 244 "math.l"
{ return NRT; }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 245 "math.l"
{ return SRT; }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 247 "math.l"
{ return MOD; }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 248 "math.l"
{ return FLR; }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 249 "math.l"
{ return CIL; }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 250 "math.l"
{ return RND; }
	YY_BREAK
case 205:
#line 253 "math.l"
case 206:
YY_RULE_SETUP
#line 253 "math.l"
{ return SWC; }
	YY_BREAK
case 207:
#line 257 "math.l"
case 208:
#line 258 "math.l"
case 209:
YY_RULE_SETUP
#line 258 "math.l"
{ yylval = 0; return NOVR; }
	YY_BREAK
case 210:
#line 260 "math.l"
case 211:
#line 261 "math.l"
case 212:
YY_RULE_SETUP
#line 261 "math.l"
{ yylval = 1; return NOVR; }
	YY_BREAK
case 213:
#line 263 "math.l"
case 214:
#line 264 "math.l"
case 215:
YY_RULE_SETUP
#line 264 "math.l"
{ yylval = 2; return NOVR; }
	YY_BREAK
case 216:
#line 266 "math.l"
case 217:
#line 267 "math.l"
case 218:
YY_RULE_SETUP
#line 267 "math.l"
{ yylval = 3; return NOVR; }
	YY_BREAK
case 219:
#line 269 "math.l"
case 220:
#line 270 "math.l"
case 221:
YY_RULE_SETUP
#line 270 "math.l"
{ yylval = 4; return NOVR; }
	YY_BREAK
case 222:
#line 272 "math.l"
case 223:
#line 273 "math.l"
case 224:
YY_RULE_SETUP
#line 273 "math.l"
{ yylval = 5; return NOVR; }
	YY_BREAK
case 225:
YY_RULE_SETUP
#line 276 "math.l"
{ yylval = 0; return OOVR; }
	YY_BREAK
case 226:
YY_RULE_SETUP
#line 277 "math.l"
{ yylval = 1; return OOVR; }
	YY_BREAK
case 227:
YY_RULE_SETUP
#line 278 "math.l"
{ yylval = 2; return OOVR; }
	YY_BREAK
case 228:
YY_RULE_SETUP
#line 279 "math.l"
{ yylval = 3; return OOVR; }
	YY_BREAK
case 229:
YY_RULE_SETUP
#line 280 "math.l"
{ yylval = 4; return OOVR; }
	YY_BREAK
case 230:
#line 284 "math.l"
case 231:
#line 285 "math.l"
case 232:
#line 286 "math.l"
case 233:
YY_RULE_SETUP
#line 286 "math.l"
{ yylval = 0; return OSUM; }
	YY_BREAK
case 234:
#line 289 "math.l"
case 235:
#line 290 "math.l"
case 236:
#line 291 "math.l"
case 237:
YY_RULE_SETUP
#line 291 "math.l"
{ yylval = 1; return OSUM; }
	YY_BREAK
case 238:
#line 294 "math.l"
case 239:
#line 295 "math.l"
case 240:
#line 296 "math.l"
case 241:
YY_RULE_SETUP
#line 296 "math.l"
{ yylval = 2; return OSUM; }
	YY_BREAK
case 242:
#line 299 "math.l"
case 243:
YY_RULE_SETUP
#line 299 "math.l"
{ yylval = 3; return OSUM; }
	YY_BREAK
case 244:
#line 301 "math.l"
case 245:
#line 302 "math.l"
case 246:
YY_RULE_SETUP
#line 302 "math.l"
{ yylval = 4; return OSUM; }
	YY_BREAK
case 247:
YY_RULE_SETUP
#line 304 "math.l"
{ yylval = 5; return OSUM; }
	YY_BREAK
case 248:
#line 307 "math.l"
case 249:
#line 308 "math.l"
case 250:
#line 309 "math.l"
case 251:
YY_RULE_SETUP
#line 309 "math.l"
{ yylval = 6; return OSUM; }
	YY_BREAK
case 252:
#line 312 "math.l"
case 253:
#line 313 "math.l"
case 254:
#line 314 "math.l"
case 255:
YY_RULE_SETUP
#line 314 "math.l"
{ yylval = 7; return OSUM; }
	YY_BREAK
case 256:
YY_RULE_SETUP
#line 316 "math.l"
{ yylval = 8; return OSUM; }
	YY_BREAK
case 257:
YY_RULE_SETUP
#line 317 "math.l"
{ yylval = 9; return OSUM; }
	YY_BREAK
case 258:
YY_RULE_SETUP
#line 320 "math.l"
{ return FR; }
	YY_BREAK
case 259:
YY_RULE_SETUP
#line 321 "math.l"
{ return TO; }
	YY_BREAK
case 260:
#line 323 "math.l"
case 261:
YY_RULE_SETUP
#line 323 "math.l"
{ return WH; }
	YY_BREAK
case 262:
YY_RULE_SETUP
#line 326 "math.l"
{ return SPC; }
	YY_BREAK
case 263:
YY_RULE_SETUP
#line 327 "math.l"
{ return SEP; }
	YY_BREAK
case 264:
YY_RULE_SETUP
#line 328 "math.l"
{ return SNL; }
	YY_BREAK
case 265:
YY_RULE_SETUP
#line 329 "math.l"
{ return ALG; }
	YY_BREAK
case 266:
/* rule 266 can match eol */
YY_RULE_SETUP
#line 330 "math.l"
{ /* return EOL; */ }
	YY_BREAK
case 267:
YY_RULE_SETUP
#line 331 "math.l"
{ }
	YY_BREAK
case 268:
YY_RULE_SETUP
#line 332 "math.l"
{ printf("Unknown: %c\n", *yytext); }
	YY_BREAK
case 269:
YY_RULE_SETUP
#line 334 "math.l"
ECHO;
	YY_BREAK
#line 2147 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 667 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 667 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 666);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 334 "math.l"

